### ISSUE TITLE
Weird article ids?

### ISSUE THREAD

**Issue by wtfnzb** [mbruel/ngPost#1]
Why article number has { and } ? how to remove them?

`<segment bytes="blabla" number="blabla">{019b929b-blabla-438f-bab2-blabla}@blabla</segment>`

**Comment by mbruel** [comment]
hello,
what's wrong with the curly bracket? why does it bother you? does it make an issue with some news readers? if so please tell me which one.
I'm just using UUIDs as Qt generate them... https://en.wikipedia.org/wiki/Universally_unique_identifier

**Comment by wtfnzb** [comment]
all good then, somehow it taken longer to propagate articles but all works great! :)

**Comment by mbruel** [comment]
I've removed the curly brackets and dashes in the v1.2 release.
It can be done easily using Qt string format QUuid::StringFormat::Id128.
cf https://doc.qt.io/qt-5/quuid.html#StringFormat-enum

**Comment by wtfnzb** [comment]
thx! :)
