### ISSUE TITLE
[Request] Add a --nfo option

### ISSUE THREAD

**Issue by awsms** [mbruel/ngPost#10]
Adding a --nfo paramater (--nfo file.nfo) so the .nfo file won't be splitted in the rest of the archive, and indexers will be able to identify it.

**Comment by mbruel** [comment]
could give more details plz?
if the nfo is accessible, isn't unproductive as the whole post would be spotted and thus removed due to DMCA complaints?

**Comment by awsms** [comment]
Yes I know about the DMCA, but it will be more effecient to spread new releases. It's still a plus to have that function in the program.
By the way, is there a way to randomize the names of the files archived (inside the archives), or I'll have to rename them myself before posting?

**Comment by mbruel** [comment]
> Yes I know about the DMCA, but it will be more effecient for spreading new releases, and it's still a plus to have that function in the program.

well don't your providers report the DMCA complaints to you and threaten to suspend your account if you continue posting copyrighted content? I got such warning with newshosting doing some tests and using zip format to compress with a password but the header was not protected so you could see what's inside...

>  By the way, is there a way to randomize the names of the files archived (inside the archives), or I'll have to rename them myself before posting?

why would you need that? don't you use a password with rar?

**Comment by Uukrull** [comment]
Or even better: with the obfuscation option, a password isn't even needed because it is literally impossible to find the posting without the nzb.

**Comment by lollilol** [comment]
please dont obfuscate your file names. its a really pain in the ass and its much easier for you and the leecher to just put a password on your rar file.

**Comment by mbruel** [comment]
> please dont obfuscate your file names. its a real pain in the ass and its much easier for you and the leecher to just put a password on your rar file.

Totally agree... Someone asked me to add the feature so I did but yeah best practice nowadays is to use a password...

> When you leech with sabnzbd you can put the rar password in the nzb file in the nzb like: {{randomrarpassword}}.nzb

The password is in the header of the nzb, no need to add it in the name of the file ;)

**Comment by Tensai75** [comment]
> The password is in the header of the nzb, no need to add it in the name of the file ;)

Hi Matthieu,

„Title{{Password}}.nzb“ is actually a widely used naming scheme for NZB files. And I think some Usenet Downloader Programs still don’t read out the password from the meta information but rely on the file name to extract the password.
Would be nice if ngPost would have an option to save the NZB file with the password also in the file name.

Regards, Tensai

**Comment by DEVUVO** [comment]
> Adding a --nfo paramater (--nfo file.nfo) so the .nfo file won't be splitted in the rest of the archive, and indexers will be able to identify it.

Try to do it manual by rename all your nfo files before posting to match the name you want , it's not hard at all you can use BRU or any other tools , and you can also post it by separate email . NFO is important yes but if you want to keep things private if it's work files or anything else this is NOT a good idea , we need to focus on the most important features at the moment and maybe later we can see about nfo  , or maybe later there is going to be option to upload a copy of the .nfo files before rarring the whole thing and add the password , but now yes we need to focus if there is anything important missing or any bugs . so far so good , can't wait till next version :)
