### ISSUE TITLE
job queue is not working correctly

### ISSUE THREAD

**Issue by stringer44** [mbruel/ngPost#100]
Hello. I use latest version. And have a trouble with job queue. I am running multiple jobs but only one job is running. other tasks are paused, even when the first task is completed. please fix it :) 
on  v4.9_x64 haven't this issue.

**Comment by mbruel** [comment]
hum, weird, you seem to be the only one reporting that issue....
what OS? GUI or CLI?
What mode do you use? Auto Posting, Monitoring, single QuickPost you define?

**Comment by stringer44** [comment]
> hum, weird, you seem to be the only one reporting that issue....
> what OS? GUI or CLI?
> What mode do you use? Auto Posting, Monitoring, single QuickPost you define?

Win10 x64 GUI
I use tabs "quick post" and "new". then press "post files" button in every tab. and only one job working. The rest of the tasks will be paused until I press "cancel" and "post" again
sorry my english, i use google translate.

**Comment by mbruel** [comment]
I don't have any issue doing several QuickPosts... They start after each others..
is the icon of the pending posts changing to this one: ![](https://raw.githubusercontent.com/mbruel/ngPost/master/src/resources/icons/pending.png)
Is your config up to date? do you use `PREPARE_PACKING = true` ?
Anyway there is only one post at a time, and the progress bar is reset to 0 when the current one is done and we start the next one. Are you sure you're waiting long enough?

**Comment by mbruel** [comment]
is doing it every time?
you sure there wasn't an error during the compression or the par2 generation of the second post?
I'm not sure if it would resume in that case...
can you please activate "show debug info" and set the level to 2. Then post me a snapshot when the first one is finished and the others in pause and also the content of debug infos.

**Comment by mbruel** [comment]
@stringer44 any news? do you still have the issue?

**Comment by stringer44** [comment]
hello
sorry for delay

log is here, bug still present. v4.14, win10. quickpost1 was uploaded, quickpost2 doesn't start

[Poster #0] threads quit
[Poster #0] connection thread done
[Poster #0] threads stopped
[Poster #1] threads quit
[Poster #1] connection thread done
[Poster #1] threads stopped
All posters stopped...
[Poster #0] threads quit
[Poster #0] connection thread done
[Poster #0] threads stopped
[Poster #1] threads quit
[Poster #1] connection thread done
[Poster #1] threads stopped
All posters stopped...
Deleting PostingJob
[Poster #0 {NntpCon #13}] Destructing connection..
[Poster #0 {NntpCon #4}] Destructing connection..
[Poster #0 {NntpCon #7}] Destructing connection..
[Poster #0 {NntpCon #2}] Destructing connection..
[Poster #1 {NntpCon #26}] Destructing connection..
[Poster #1 {NntpCon #22}] Destructing connection..
[Poster #1 {NntpCon #29}] Destructing connection..
[Poster #1 {NntpCon #23}] Destructing connection..
[Poster #0 {NntpCon #6}] Destructing connection..
[Poster #0 {NntpCon #15}] Destructing connection..
[Poster #1 {NntpCon #19}] Destructing connection..
[Poster #1 {NntpCon #17}] Destructing connection..
[Poster #0 {NntpCon #5}] Destructing connection..
[Poster #1 {NntpCon #28}] Destructing connection..
[Poster #0 {NntpCon #8}] Destructing connection..
[Poster #1 {NntpCon #25}] Destructing connection..
[Poster #1 {NntpCon #30}] Destructing connection..
[Poster #1 {NntpCon #24}] Destructing connection..
[Poster #0 {NntpCon #10}] Destructing connection..
[Poster #1 {NntpCon #21}] Destructing connection..
[Poster #1 {NntpCon #27}] Destructing connection..
[Poster #1 {NntpCon #16}] Destructing connection..
[Poster #0 {NntpCon #3}] Destructing connection..
[Poster #1 {NntpCon #18}] Destructing connection..
[Poster #0 {NntpCon #12}] Destructing connection..
[Poster #0 {NntpCon #9}] Destructing connection..
[Poster #0 {NntpCon #1}] Destructing connection..
[Poster #0 {NntpCon #14}] Destructing connection..
[Poster #0 {NntpCon #11}] Destructing connection..
[Poster #1 {NntpCon #20}] Destructing connection..
[Poster #0] threads quit
[Poster #0] connection thread done
[Poster #0] threads stopped
[Poster #1] threads quit
[Poster #1] connection thread done
[Poster #1] threads stopped

**Comment by stringer44** [comment]
hello. sorry for delay
big still presents
log is here
quickpost 2 and 3 were started
quickpost2 was uploaded, quickpost3 doesn't start automatically. v4.14 x64 win10

[Poster #0] threads quit
[Poster #0] connection thread done
[Poster #0] threads stopped
[Poster #1] threads quit
[Poster #1] connection thread done
[Poster #1] threads stopped
All posters stopped...
[Poster #0] threads quit
[Poster #0] connection thread done
[Poster #0] threads stopped
[Poster #1] threads quit
[Poster #1] connection thread done
[Poster #1] threads stopped
All posters stopped...
Deleting PostingJob
[Poster #1 {NntpCon #28}] Destructing connection..
[Poster #1 {NntpCon #16}] Destructing connection..
[Poster #1 {NntpCon #22}] Destructing connection..
[Poster #1 {NntpCon #25}] Destructing connection..
[Poster #1 {NntpCon #29}] Destructing connection..
[Poster #1 {NntpCon #20}] Destructing connection..
[Poster #1 {NntpCon #23}] Destructing connection..
[Poster #1 {NntpCon #21}] Destructing connection..
[Poster #1 {NntpCon #27}] Destructing connection..
[Poster #1 {NntpCon #18}] Destructing connection..
[Poster #1 {NntpCon #26}] Destructing connection..
[Poster #0 {NntpCon #12}] Destructing connection..
[Poster #0 {NntpCon #6}] Destructing connection..
[Poster #0 {NntpCon #8}] Destructing connection..
[Poster #0 {NntpCon #14}] Destructing connection..
[Poster #1 {NntpCon #30}] Destructing connection..
[Poster #0 {NntpCon #3}] Destructing connection..
[Poster #0 {NntpCon #10}] Destructing connection..
[Poster #1 {NntpCon #17}] Destructing connection..
[Poster #1 {NntpCon #24}] Destructing connection..
[Poster #0 {NntpCon #5}] Destructing connection..
[Poster #0 {NntpCon #15}] Destructing connection..
[Poster #1 {NntpCon #19}] Destructing connection..
[Poster #0 {NntpCon #11}] Destructing connection..
[Poster #0 {NntpCon #13}] Destructing connection..
[Poster #0 {NntpCon #2}] Destructing connection..
[Poster #0 {NntpCon #7}] Destructing connection..
[Poster #0 {NntpCon #4}] Destructing connection..
[Poster #0 {NntpCon #1}] Destructing connection..
[Poster #0 {NntpCon #9}] Destructing connection..
[Poster #0] threads quit
[Poster #0] connection thread done
[Poster #0] threads stopped
[Poster #1] threads quit
[Poster #1] connection thread done
[Poster #1] threads stopped

**Comment by mbruel** [comment]
Do you use compression in the QuickPosts?

**Comment by stringer44** [comment]
> Do you use compression in the QuickPosts?

no, i use app only for upload

**Comment by mbruel** [comment]
hum, that's the issue then.
I'm going to build you a fix so you can try with some extra logs

**Comment by mbruel** [comment]
@stringer44 otherwise you can just disable `PREPARE_PACKING` in the config and it should work as the previous version ;)

**Comment by stringer44** [comment]
> @stringer44 otherwise you can just disable `PREPARE_PACKING` in the config and it should work as the previous version ;)

thank you sir :) yes, previous version worked fine, i'll try to disable that feature in latest version next time.

**Comment by mbruel** [comment]
@stringer44 it should work without `PREPARE_PACKING` but otherwise, could you also try to let it and replace the `ngPost.exe` in the installation folder with [this one](https://files.fm/f/x9py3zd7y)
Using Debug info with level 2, you should see this log:
`start non packing job...`
please confirm,
and feel free to give a little donation if you can ;)

**Comment by traktor87** [comment]
@mbruel I also use your programm just for posting (nonrar content). I tried with the way you proposed (I replaced ngPost.exe) and it worked just for the QuickPost #2, while QuickPost #3 (and later posts) doesn't start (waiting time icon). I got this message: "next active job different to the packing one..."


.
.
.
[Poster #4] threads stopped
[Poster #5] threads quit
[Poster #5] connection thread done
[Poster #5] threads stopped
All posters stopped...


**next active job different to the packing one...**

Deleting PostingJob
[Poster #1 {NntpCon #7}] Destructing connection..
[Poster #3 {NntpCon #16}] Destructing connection..
[Poster #3 {NntpCon #17}] Destructing connection..
[Poster #5 {NntpCon #30}] Destructing connection..
[Poster #4 {NntpCon #25}] Destructing connection..
[Poster #3 {NntpCon #20}] Destructing connection..
[Poster #4 {NntpCon #24}] Destructing connection..
[Poster #4 {NntpCon #22}] Destructing connection..
[Poster #5 {NntpCon #27}] Destructing connection..
[Poster #4 {NntpCon #21}] Destructing connection..
[Poster #5 {NntpCon #29}] Destructing connection..
[Poster #3 {NntpCon #18}] Destructing connection..
[Poster #4 {NntpCon #23}] Destructing connection..
[Poster #5 {NntpCon #28}] Destructing connection..
[Poster #3 {NntpCon #19}] Destructing connection..
[Poster #5 {NntpCon #26}] Destructing connection..
[Poster #2 {NntpCon #14}] Destructing connection..
[Poster #2 {NntpCon #12}] Destructing connection..
[Poster #2 {NntpCon #15}] Destructing connection..
[Poster #1 {NntpCon #10}] Destructing connection..
[Poster #2 {NntpCon #11}] Destructing connection..
[Poster #1 {NntpCon #8}] Destructing connection..
[Poster #2 {NntpCon #13}] Destructing connection..
[Poster #0 {NntpCon #2}] Destructing connection..
[Poster #0 {NntpCon #5}] Destructing connection..
[Poster #1 {NntpCon #9}] Destructing connection..
[Poster #0 {NntpCon #1}] Destructing connection..
[Poster #0 {NntpCon #3}] Destructing connection..
[Poster #0 {NntpCon #4}] Destructing connection..
[Poster #1 {NntpCon #6}] Destructing connection..
[Poster #0] threads quit
[Poster #0] connection thread done
[Poster #0] threads stopped
[Poster #1] threads quit
[Poster #1] connection thread done
[Poster #1] threads stopped
[Poster #2] threads quit
[Poster #2] connection thread done
[Poster #2] threads stopped
[Poster #3] threads quit
[Poster #3] connection thread done
[Poster #3] threads stopped
[Poster #4] threads quit
[Poster #4] connection thread done
[Poster #4] threads stopped
[Poster #5] threads quit
[Poster #5] connection thread done
[Poster #5] threads stopped


I hope you can see into this and thank you for even considering,

**Comment by mbruel** [comment]
@traktor87 @stringer44 indeed I forgot something... try [this version](https://files.fm/f/xhxg2vjy8). I've tested with 4 things to post without compression and it seems to work. please confirm and [feel free to donate](https://github.com/mbruel/ngPost#donations) to support the work ;)

**Comment by traktor87** [comment]
Thank you mbruel, now it works! I also donated because I appreciate your work :)

**Comment by mbruel** [comment]
thanks man ;)
I'll make a proper release soon.
