### ISSUE TITLE
Incomplete upload

### ISSUE THREAD

**Issue by Mibix** [mbruel/ngPost#101]
I uploaded something and it seems to have worked (ngPost_v4.14 says 100% and I can download it successfully) but binsearch says the following:
size: 28.87 GB, parts available: 41999 / 42011
99 rar files
13 par2 files

I am not sure how it is missing parts?  None of the other indexers will pick up incompletes

**Comment by mbruel** [comment]
well no big deal if few articles are missing, par2 are there for that.
maybe binsearch is just taking a bit more time to synchronize all the articles. Have you tried like 24h after the post?

**Comment by Mibix** [comment]
![image](https://user-images.githubusercontent.com/7806070/109136032-b0e19080-7725-11eb-921c-93286d825999.png)
its only been 17 hours but its weird it shows 100% here I guess I will wait and see

**Comment by mbruel** [comment]
and in the log it doesn't says few articles failed to be posted?

**Comment by Mibix** [comment]
No I don't see anything on the right in the posting log.  Is there a more detailed log somewhere?

**Comment by mbruel** [comment]
no, if there is nothing in red saying an article failed to be posted, it's ok.
well don't know why binsearch missed few of them...
what about nzbindex?

**Comment by Mibix** [comment]
nzbindex says its complete interesting
