### ISSUE TITLE
Bug: Newsgroup list ignored, post appears only in one group

### ISSUE THREAD

**Issue by UsefulVid** [mbruel/ngPost#106]
I uploaded an open source software
![grafik](https://user-images.githubusercontent.com/39967070/113343164-c010bb00-932f-11eb-84f6-09c9ecbc50ad.png)

But it only appears in group "misc" and not "test"

![grafik](https://user-images.githubusercontent.com/39967070/113343242-dae32f80-932f-11eb-977d-76d932db5406.png)
(Uploaded Software is syncthing)
K0Kax9yHdbnTcB5cQhA5hD

**Comment by mbruel** [comment]
There is configuration file...
Check [GROUP_POLICY](https://github.com/mbruel/ngPost/blob/master/ngPost.conf) I guess you've let the default option.

**Comment by mbruel** [comment]
@UsefulVid it's also explained in the [README here[(https://github.com/mbruel/ngPost#configuration-file-and-keywords-that-are-only-in-config)
