### ISSUE TITLE
GUI improvement: contradictory options GUI vs. Config File

### ISSUE THREAD

**Issue by UsefulVid** [mbruel/ngPost#107]
The config files seems to overwrite settings in the GUI in a incomprehensible way:
https://github.com/mbruel/ngPost/issues/106#issuecomment-812754623

Having 2 different locations where you can set options seems to be a confusing way to handle things.
Why is it possible to enter 2 Groups when actually only one is allowed by the config file?
Why not just allow a single group to be entered as long as only one is allowed by the config file?
Furthermore, the post did appear on "misc" and not n "test". Test was the first place and misc the second.

**Comment by mbruel** [comment]
For most users groups are not important, only the nzb is...
Read the doc about GROUP_POLICY, just set it to ALL if you want to post on several groups.
Most people prefer to post only on one that is random from the list. There is no contradiction...

**Comment by mbruel** [comment]
@UsefulVid do you find it easier if I set the default option to ALL?
ngPost is normally targeting kind of experimented Usenet people and I suppose that new users come from a community where there is a tutorial or people that can explain how it works. Am I wrong?
