### ISSUE TITLE
Separate NZB for each folder or file

### ISSUE THREAD

**Issue by zuricarmi** [mbruel/ngPost#108]
Hi
I have many folders (each folder is >2Giga in size)
I add them to the GUI
but it will upload all of them in the same NZB and in any problem while uploads all the prosses needs to start again
please add in the GUI the option to create separate NZB for each Folder in the list (of for each file in file list)
Thanks

**Comment by AnythingOldSkewl** [comment]
You should be able to do this by using the "AutoPosting" tab.
