### ISSUE TITLE
Only Posts To A Single NewsGroup?

### ISSUE THREAD

**Issue by AnythingOldSkewl** [mbruel/ngPost#109]
Not sure if this is a bug or not, but ngPost appears to only upload content to a single newsgroup, despite having several listed... (I made sure there were no spaces anywhere)

I can also look in the NZB file and it almost always picks the first newsgroup from a list of 9. By chance, are we still using comas? Or have they been replaced with something else?

**Comment by mbruel** [comment]
duplicate of #106 
change the GROUP_POLICY if you want.

**Comment by AnythingOldSkewl** [comment]
OOOOHHHH I see... Thanks.. I didn't notice this until recently. 👍
