### ISSUE TITLE
[Feature Request] Server for Header Check

### ISSUE THREAD

**Issue by theHornest** [mbruel/ngPost#111]
it would be great if there was the possibility to choose one server for uploading and one for header check.
thank you for your work

**Comment by mbruel** [comment]
well that's boring to implement, it breaks the way I'm parsing the config file.
Easy way to do it: just create a conf file dedicated to header check and use `ngPost -c <your conf for header check> --check <your nzb>`
you can also make an alias like `alias checknzb='ngPost -c <your conf for header check> --check'`
