### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by theHornest** [mbruel/ngPost#113]
When i start uploading i get this Message

`[Poster #1 {NntpCon #5}] Error SSL Socket: - The host name did not match any of the valid hosts for this certificate `

**Comment by mbruel** [comment]
Is it doing it all the time?
Is it posting something even if you get few errors?
Which provider do you use? what OS?

**Comment by theHornest** [comment]
> Is it doing it all the time?
yes
> Is it posting something even if you get few errors?
no
> Which provider do you use? what OS?
dreamload.com on Windows

**Comment by mbruel** [comment]
Try to contact them and give them the error.
I think they've an issue on their side.
Can you post on the port 119 without SSL?

**Comment by theHornest** [comment]
> Try to contact them and give them the error.
> I think they've an issue on their side.
hmm, strange, with JBinUp there are no problems with SSL upload

> Can you post on the port 119 without SSL?
yes, it works without any problems

**Comment by mbruel** [comment]
>  hmm, strange, with JBinUp there are no problems with SSL upload

well there might be an option on the socket to ignore a bad certificate but all providers should have a proper one...
only small website or individuals have self-signed certificates...
It could be done ([cf this thread](https://stackoverflow.com/questions/33344845/how-to-ignore-ssl-error-in-qt-based-tcp-server-client-application)) but I won't make ngPost less secure for them ;)
