### ISSUE TITLE
How to post without passwording rar in command line

### ISSUE THREAD

**Issue by Sonic3R** [mbruel/ngPost#114]
I want to post to a newsgroup without setting a password to rar/archive in command line:

I use following arguments:
`-t 1 -h mynewsgroup.com -P 563 -s -u USER -p PASS -n 30 -f whocares@nowhere.com  -g \"alt.binaries.test,alt.binaries.test2\" -a 64000 -i PATH_TO_FOLDER -o MY_OUTPUT.nzb`

In the UI, I can uncheck this:
![image](https://user-images.githubusercontent.com/6311947/119977219-ce422700-bfc0-11eb-9f91-e960285b72b7.png)

**Comment by mbruel** [comment]
check your configuration file, set `AUTO_COMPRESS` to false or comment it.
For the next version the keyword will be different, `PACK` will be used instead. [cf here](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L145)

**Comment by Sonic3R** [comment]
Would be nice that option must be present in command line. If is not present then don't use it, even or no matter what config file says. 

Modifying such parameter work now but still would be nice to leave to user if want to password content or not through command line

**Comment by mbruel** [comment]
well you just need to unset the keyword in the config file...
`## Auto compression for all posts with random archive name, password and par2 generation`
If it is set, `--compress --gen_par2 --gen_name --gen_pass` is added to the command automatically. That's quite handy!
If you don't want it, unset `AUTO_COMPRESS`
With the new version it will be better with `--pack` for the command line that is linked to the configuration file.
I'm not sure when I'll release it... I'm in vacation for a few weeks.
