### ISSUE TITLE
Can't post using 7zip

### ISSUE THREAD

**Issue by Kcchouette** [mbruel/ngPost#115]
Hello

When I specify rar binarie, it's ok:
```
Compressing files: /usr/bin/rar a -ep1 -m0 -idp -XXXXX /tmp/usenet/YYYY/YYYYY.rar file.txt

*******

Generating par2: /tmp/.mount_ngPost/par2 c -l -m1024 -r10 /tmp/usenet/YYYYY/YYYYY.par2 /tmp/usenet/YYYYY/YYYYY*rar -q
****************************
```

but using 7zip (7z OR 7za) it failed (fulldebug):
```
Compressing files: /usr/bin/7z a -mx0 -mhe=on -XXXXX /tmp/usenet/YYYYY/YYYYY.7z file.txt


7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs x64)

Scanning the drive:
1 file, ZZZZZ bytes (ZZZZ MiB)

Creating archive: /tmp/usenet/YYYYY/YYYYY.7z

Items to compress: 1


Files read from disk: 1
Archive size: ZZZZ bytes (ZZZZ MiB)
Everything is Ok
=> rar exit code: 0

[16:54:19.612] Generating par2: /tmp/.mount_ngPost/par2 c -l -m1024 -r10 /tmp/usenet/YYYYY/YYYYY.par2 /tmp/usenet/YYYYY/YYYYY.7z* -q
You must specify a list of files when creating.

=> par2 exit code: 3

```

Cheers

**Comment by Kcchouette** [comment]
Only difference between the two commands are: `--rar_path "/usr/bin/7z"` or `--rar_path "/usr/bin/rar"`

**Comment by mbruel** [comment]
@Kcchouette  what OS, what ngPost version?

**Comment by Kcchouette** [comment]
ngPost v4.14, AppImage version
I'm under archlinux

**Comment by mbruel** [comment]
I think I fixed that. Please try [this beta of the v4.15](https://files.fm/f/3pppawzat) and let me know if it's all good.
I've no issue on my env.
(AUTO_COMPRESS is not used anymore, you should use PACK instead ([cf here](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L145)) and if you want to use it in command line you need to add --pack)

**Comment by Kcchouette** [comment]
Hello

I can not test, here the error I have:

```
PACKing auto using: 
Do article obfuscation (the subject of each Article will be a UUID)


[21:27:09.226] Start posting: file.nzb
[21:27:09.226] Generating par2: /tmp/.mount_ngPostBZAbQn/par2 c -l -m1024 -r10 -B /home/user/Downloads /home/user/tmp/file/file.par2 /home/user/Downloads/file
Invalid option specified: -B



Error during par2 generation: 3
```

**Comment by mbruel** [comment]
@Kcchouette hum ok you use `par2` and not `parpar`...
can you write your full ngPost command please. So I guess you don't use `PAR2_ARGS` ? Can you please also post your configuration file.
cheers ;)

PS: why don't you use parpar, it's muuuch faster ;)

**Comment by Kcchouette** [comment]
command: `ngPost_v4.15_beta1-x86_64.AppImage --obfuscate --groups "xxxx" --gen_from --pack COMPRESS,GEN_NAME,GEN_PASS,GEN_PAR2 --length_pass 20 --par2_pct 10 --tmp_dir "/home/user/tmp" --rar_path "/usr/bin/rar" --conf "/home/user/ngPost.conf" --output "file.nzb" --input "file"`

configuration: 
```
POST_HISTORY = file.csv
FIELD_SEPARATOR = ,

[server]
host = xxxx
port = xxxx
ssl  = true
user = xxxx
pass = xxxx
connection = xx
enabled = true
nzbCheck = false
```

**Comment by mbruel** [comment]
hum what's your OS and par2 version?
sounds like it doesn't recognize the `-B`.
I don't have any issue on my env:
```
$par2 -V
par2cmdline version 0.8.0
$ par2 --help
Usage:
  par2 -h  : show this help
...
Options:

  -a<file> : Set the main PAR2 archive name
...
  -B<path> : Set the basepath to use as reference for the datafiles
  --       : Treat all following arguments as filenames
```

Please try the par2 command without ngPost after checking the `-B` is available.
You've only that in your config? oO
you could put most things of your command line in it ([cf the example](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L145))

`--pack` does't take any argument. maybe it wasn't clear. It relies on the configuration file where the PACK keyword should be defined.
So add `PACK = COMPRESS, GEN_NAME, GEN_PASS, GEN_PAR2` in your conf and you'll be able to use `--pack`. Otherwise you need to write the whole `--compress --gen_name --gen_pass --gen_par2`
I hope it is clear...

Don't use `--obfuscate`, it can be considered as spam and it is not needed as you use a password...
with a good config file (that can be ~/.ngPost) your command could just be:
`ngPost_v4.15_beta1-x86_64.AppImage --pack -i "file" -o "file.nzb"`

**Comment by mbruel** [comment]
hum my bad you're using the par2 included in ngPost which is quite old...
```
~/ngPost/release/ngPost$ ./par2 -V
par2cmdline version 0.6.14
```
I gonna update that thanks ;)

**Comment by mbruel** [comment]
[try this version](https://files.fm/f/ej37d457u), should be fine ;)
but please update your config, at least with the PACK keyword.
and forget about the --obfuscate. No need!

**Comment by mbruel** [comment]
PS: please confirm so I can close this issue

**Comment by mbruel** [comment]
PS2: please try also with 7zip to make sure everything works

**Comment by Kcchouette** [comment]
So using rar is fine:
```
PACKing auto using: COMPRESS, GEN_NAME, GEN_PASS, GEN_PAR2


[22:21:19.370] Start posting: file.nzb
[22:21:19.371] Compressing files: /usr/bin/rar a -ep1 -m0 -idp -hp4BOBcCu4ru4BgtxrBxwp /home/user/tmp/xNTAHoo4kfrt9LvDi/xNTAHoo4kfrt9LvDi.rar /home/user/Downloads/file

*******

[22:21:19.645] Generating par2: /tmp/.mount_ngPost1WFoBi/par2 c -l -m1024 -r10 /home/user/tmp/xNTAHoo4kfrt9LvDi/xNTAHoo4kfrt9LvDi.par2 /home/user/tmp/xNTAHoo4kfrt9LvDi/xNTAHoo4kfrt9LvDi*rar -q
****************************

[22:21:22.617] Number of available Nntp Connections: 40

[22:21:25.233] Upload size: 27.14 MB in 00:00:02.616 (2 sec)                  => average speed:  10.38 MB/s (40 connections on 12 threads)
[22:21:25.233] nzb file: /home/user/file.nzb
[22:21:25.233] file: file.nzb, rar name: xNTAHoo4kfrt9LvDi, rar pass: 4BOBcCu4ru4BgtxrBxwp
```

But using 7z is still failing:

```
PACKing auto using: COMPRESS, GEN_NAME, GEN_PASS, GEN_PAR2


[22:23:31.284] Start posting: file.nzb
[22:23:31.284] Compressing files: /usr/bin/7z a -mx0 -mhe=on -p48gfwC20FRCvRZWRWmSy /home/user/tmp/n97PBcowmpumGJP1r/n97PBcowmpumGJP1r.7z /home/user/Downloads/file

**

[22:23:31.604] Generating par2: /tmp/.mount_ngPostZhmYlx/par2 c -l -m1024 -r10 /home/user/tmp/n97PBcowmpumGJP1r/n97PBcowmpumGJP1r.par2 /home/user/tmp/n97PBcowmpumGJP1r/n97PBcowmpumGJP1r.7z* -q
You must specify a list of files when creating.



Error during par2 generation: 3
```

**Comment by mbruel** [comment]
add --debug to your command in order to have the detail of 7z and par2.
Please try both commands manually:
```
mkdir /home/user/tmp/debugFolder
/usr/bin/7z a -mx0 -mhe=on -p48gfwC20FRCvRZWRWmSy /home/user/tmp/debugFolder/debugFolder.7z /home/user/Downloads/file
```
what do you have in `/home/user/tmp/debugFolder` ?

Then try:
`par2 c -l -m1024 -r10 /home/user/tmp/debugFolder/debugFolder.par2 /home/user/tmp/debugFolder/debugFolder.7z* -q`
if you don't have par2, you get it [here](https://files.fm/f/7cwazt9hk).

**Comment by Kcchouette** [comment]
## what do you have in /home/user/tmp/debugFolder ?

I have one file `debugFolder.7z`

## Then try par2 command

I have now one file `debugFolder.7z`, one file `debugFolder.par2`, and:
debugfolder.vol000+01.par2
debugfolder.vol001+02.par2
debugfolder.vol003+04.par2
debugfolder.vol007+08.par2
debugfolder.vol015+16.par2
debugfolder.vol031+32.par2
debugfolder.vol063+64.par2
debugfolder.vol127+73.par2

## add --debug to your command in order to have the detail of 7z and par2

```
Extra logs are ON
PACKing auto using: COMPRESS, GEN_NAME, GEN_PASS, GEN_PAR2
Generate new random poster for each post
+ File to compress: file


[23:17:36.335] Start posting: file.nzb
[23:17:36.335] Compressing files: /usr/bin/7z a -mx0 -mhe=on -pXSCqqv0YVZ0VXIWsZDkS /home/user/tmp/DXRs24DT55UxJTDkp/DXRs24DT55UxJTDkp.7z /home/user/Downloads/file


7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs x64)

Scanning the drive:
1 file, 24539952 bytes (24 MiB)

Creating archive: /home/user/tmp/DXRs24DT55UxJTDkp/DXRs24DT55UxJTDkp.7z

Items to compress: 1


Files read from disk: 1
Archive size: 24540307 bytes (24 MiB)
Everything is Ok
=> rar exit code: 0

[23:17:36.669] Generating par2: /tmp/.mount_ngPost86cjg7/par2 c -l -m1024 -r10 /home/user/tmp/DXRs24DT55UxJTDkp/DXRs24DT55UxJTDkp.par2 /home/user/tmp/DXRs24DT55UxJTDkp/DXRs24DT55UxJTDkp.7z* -q
You must specify a list of files when creating.

=> par2 exit code: 3

Error during par2 generation: 3
Compressed files deleted.
```

**Comment by mbruel** [comment]
which is your 7z version? do --help to get it.
I've tried with mine (7-Zip [64] 16.02 ) and I don't see any issue... [here it is](https://files.fm/f/49kexg8sw) if you want to try.

```
[PostingJob::onStartPosting] Starting compression...
postSize: 53 MB => volSize: 42
[23:17:33.361] Compressing files: /usr/bin/7z a -mx0 -mhe=on -pLvf4DA5AXs7iFvp0rIEwTBsPh -v42m /tmp/0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj/0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.7z /home/bruel/Downloads/testNgPost -r

[PostingJob::_compressFiles] compression started...
lastMajor:  4 , lastMinor:  14  (currentMajor:  4 , currentMinor:  14 )

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_GB.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (906E9),ASM,AES-NI)

Scanning the drive:
6 folders, 11 files, 55793928 bytes (54 MiB)

Creating archive: /tmp/0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj/0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.7z

Items to compress: 17


Files read from disk: 11
Archive size: 55794649 bytes (54 MiB)
Everything is Ok
=> rar exit code: 0

[PostingJob::_compressFiles] compression finished...
[23:17:33.837] Generating par2: /usr/bin/par2 c -l -m1024 -r5 /tmp/0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj/0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.par2 /tmp/0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj/0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.7z* -q

Block size: 27912
Source file count: 2
Source block count: 2000
Redundancy: 5%
Recovery block count: 100
Recovery file count: 7

Opening: 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.7z.002
Opening: 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.7z.001
Computing Reed Solomon matrix.
Constructing: done.
Wrote 2791200 bytes to disk
Writing recovery packets
Writing verification packets
Done
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.7z.001
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.7z.002
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.par2
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.vol000+01.par2
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.vol001+02.par2
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.vol003+04.par2
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.vol007+08.par2
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.vol015+16.par2
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.vol031+32.par2
  - 0eiY7tRfD7Xw7LX0Ix8fPFN975gpjFnXj.vol063+37.par2
```

**Comment by Kcchouette** [comment]
in the debug above, it's indicated `7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28`

I can't load your 7z, if I use yours I have:
```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs AMD Ryzen 5 3600 6-Core Processor               (870F10),ASM,AES-NI)

Can't load '/home/user/7z.dll' (/home/user/7z.so: cannot open shared object file: No such file or directory)


ERROR:
7-Zip cannot find the code that works with archives.

=> rar exit code: 2
```

**Comment by mbruel** [comment]
@Kcchouette alright try this [beta3](https://files.fm/f/67hdqncvw), it should be fine now. strange behaviour of 7z when launched by a process if there is only one archive (not cut)... I've added some lines to handle it separately.
Please confirm all good now ;)

**Comment by Kcchouette** [comment]
Perfect :+1:
Thank you very much
It's weird that I didn't reproduce manually above

**Comment by mbruel** [comment]
yeah it's strange, manually in the cmd 7z is happy but via an external process no... not sure why. instead of loosing time trying to figure it out, it's faster to make it happy...
