### ISSUE TITLE
Folder monitor will not wait until the folder is copied over?

### ISSUE THREAD

**Issue by IITuxtmuxII** [mbruel/ngPost#117]
I use in rutorrent with autotools to copy the downloaded torrents to the monitored upload dir, but it it starts to early.
Is there a way that I can fix that?
Season folder around 40GB

OS debian
ngpost version: 4.14 appimg

**Comment by mbruel** [comment]
what so you copy? a folder with several files?
can't you move instead of copying?
at what kind of percentage is it starting? (it kicks at like 1GB/40GB or more in the middle or close to the end?)
there is a 1sec wait to check the evolution of the new incoming files/folders. It should be more than enough. Some testers tried using Samba and it was working... You could try to increase that `sMSleep` but 1sec should be more than enough...

**Comment by IITuxtmuxII** [comment]
Hi thanks for the replie,
I copy a folder with several files ca. 3GB each and it started at around 18GB of 25GB
Unforunatly I can not move the files because I have to seed.
do I have to set it in the .ngpost config?
thanks for your help.

**Comment by mbruel** [comment]
it's not in the config, the 1sec delay is hardcoded in the code. normally is more than enough.
try [this beta of the v4.15](https://files.fm/f/3pppawzat) I've just built. I made the delay to 3sec for you to try.
Let me know if it's better.
Do you have the issue all the time, frequently or rarely?

**Comment by IITuxtmuxII** [comment]
Thanks I will try the new built.^^
it depends, it only happens when it auto copies it into an empty folder it which is not uncommen.
(AUTO_COMPRESS is not used anymore, you should use PACK instead (cf here) and if you want to use it in command line you need to add --pack) I will use that thanks and have a nice day.

**Comment by AssRap3r** [comment]
> I copy a folder with several files ca. 2GB each and it started at around 18GB of 25GB
> Unforunatly I can not move the files because I have to seed.

why not set autotools to create a soft link in the monitored folder? it's faster and there's no need to copy plus you can still seed from the original directory

**Comment by mbruel** [comment]
@IITuxtmuxII any better with this extended delay? please give me feedback asap so I see if I keep the change for ngPost v4.15 that I'm ready to release. Cheers
PS: @AssRap3r comment seems relevant ;)

**Comment by IITuxtmuxII** [comment]
> @IITuxtmuxII any better with this extended delay? please give me feedback asap so I see if I keep the change for ngPost v4.15 that I'm ready to release. Cheers
> PS: @AssRap3r comment seems relevant ;)

Sorry for the late reply yes it seems to fix the issue for most of the files, but not for the large folder with small files like 100 files each 400MB, and that is because autotools does not copy them over one by one in order, but how they where finished.



why not set autotools to create a soft link in the monitored folder? it's faster and there's no need to copy plus you can still seed from the original directory
 I use rm_posted can I use it with that?
or just leave it there?

**Comment by IITuxtmuxII** [comment]
> > I copy a folder with several files ca. 2GB each and it started at around 18GB of 25GB
> > Unforunatly I can not move the files because I have to seed.
> 
> why not set autotools to create a soft link in the monitored folder? it's faster and there's no need to copy plus you can still seed from the original directory

**Comment by mbruel** [comment]
@IITuxtmuxII well
> that is because autotools does not copy them over one by one in order S01E01,S01E02,.... , but how they where finished S01E01,S01E12,S01E02 and I think that this is the main issue.

we don't care about the order. The important thing would be that the `autotools` only starts the copy when **all the subfiles are fully downloaded**. Is it the case?

give a try with the move option to see if it's any better. you could just use an `NZB_POST_CMD` to move the folder back once posted on Usenet if you wish to seed. That's the most efficient way as you don't do any copy/deletion ;)

**Comment by IITuxtmuxII** [comment]
yes autotools only copys it when it is finished downloading.
softlinking does not work sadly
well it does not work moving it because rutorrent than thinks it is only where I moved it and copying it over it would not start back up seeding.

**Comment by mbruel** [comment]
I've introduced the [new config MONITOR_SEC_DELAY_SCAN](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L59) so you can set it up to 60 sec. Maybe it will do the job. Default will be 1sec, max 120sec.
It will be available in v4.15 that should arrive soon (just waiting for german translation).
Feel free to [donate](https://github.com/mbruel/ngPost#donations) if you can to support the work ;)

**Comment by IITuxtmuxII** [comment]
thx for the help

**Comment by mbruel** [comment]
thanks for the support ;)
I've built you the last beta with the change. you can get it [here](https://files.fm/f/t873mx97t).
so as said in my previous comment, add  [MONITOR_SEC_DELAY_SCAN](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L59) in your `~/.ngPost` and try to set it to 30 or 60 and your problem should disappear. Let me know if not ;)
Cheers!
