### ISSUE TITLE
--check option doesn't work with 4.15 version

### ISSUE THREAD

**Issue by Uukrull** [mbruel/ngPost#119]
Try, for example, this [nzb](https://www.nzbking.com/details:60c615b32df7585ae41fbd16/) for an Ubuntu iso:

![image](https://user-images.githubusercontent.com/5891591/134772146-be74873e-df1e-49c3-951a-5e9f74b48c56.png)

Tested on Windows and linux and it seems https://github.com/mbruel/ngPost/commit/9f5cadc7e323f14d7ab4862777e7a1f224b08a56 is the culprit commit.

Reverting that commit, fixes the problem:

![image](https://user-images.githubusercontent.com/5891591/134772329-f92ea8cf-e5b8-4bb7-899f-95fe107129e7.png)

Btw, there is another problem not related to this particular bug that only affects Windows: if the nzb name contains a char like áé... we get the "Error opening nzb file..." message. The "tést.nzb" file is checked fine on linux but not on Windows.

**Comment by mbruel** [comment]
Indeed, my bad...
it has been corrected on github...
not sure for windows and the "special" char. I guess it was the same for v4.14 right?
I'll release soon a v4.16...

**Comment by Uukrull** [comment]
> not sure for windows and the "special" char. I guess it was the same for v4.14 right?

Yes. AFAIR it has been always the same, but never bothered to file a bug report :)

**Comment by mbruel** [comment]
what about downloading such nzb, same issue or just with `--check`?

**Comment by Uukrull** [comment]
Downloading? If you mean uploading a folder named "tést", the tést.nzb is correctly created.

**Comment by mbruel** [comment]
yeah posting...
well I had a quick look and it's boring due to windows char encoding... I've never liked those stuff... I've tried 2 or 3 things without success... [waiting for help for Qt community](https://forum.qt.io/topic/130666/issue-opening-a-qfile-on-windows-when-the-file-name-is-read-from-command-line-and-contains-accents) ;)

**Comment by Uukrull** [comment]
As a workaround, what about check all nzbs from the folder where ngPost was called if no file is added to the --check option? This way, no .bat or.sh would be needed anymore. Using your testQFileWithAccentsInName example as a base, something like this:

```
#include <QCoreApplication>
#include <iostream>
#include <cstdio>

#include <QCommandLineParser>
#include <QTextStream>
#include <QFile>
#include <QDir>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    QTextStream cout(stdout);
    QDir dir = QDir::currentPath();

    QFileInfoList fil = dir.entryInfoList( QStringList( "*.nzb" ),
                                             QDir::Files | QDir::NoDotAndDotDot | QDir::NoSymLinks,
                                             QDir::Name | QDir::IgnoreCase );
        foreach ( QFileInfo fi, fil )
        {
            // check nzb
            cout << fi.filePath() << "\n";
            QFile file(fi.filePath());
            int res = file.open(QIODevice::ReadOnly|QIODevice::Text);
            cout << (res ? QString("OK\n")
                         : QString("ERROR #%1: %2...\n").arg(file.error()).arg(file.errorString()));
        }
}

```

With test_á.nzb and test_é.nzb:

> testQFileWithAccentsInName.exe
> D:/ngPost/nzb/test_ß.nzb
> OK
> D:/ngPost/nzb/test_Ú.nzb
> OK
>

**Comment by mbruel** [comment]
well it is not that simple, the nzb checking is done asynchronously so it means quite a bit of change in the code to support several nzb one after each others...
ngPost was supposed to be a simple poster at the beginning not a toolbox.
so I'm quite lazy spending a few hours for something a script does perfectly.
and to say the truth, I'm not Windows friendly and most people doing checks I guess would be on servers running Linux.
plus we would stilll have the same issue with accents if a folder contains some (which is less likely)
so I'll see what people say on the Qt forum but no more expect if I get a donation for the job ;)

**Comment by Uukrull** [comment]
> well it is not that simple, the nzb checking is done asynchronously so it means quite a bit of change in the code to support several nzb one after each others...

I see.

I already donated but don't mind to do it again so I sent a donation with paypal.

**Comment by mbruel** [comment]
well not meaning only you... other people asked me for that feature by email...

**Comment by mbruel** [comment]
thanks anyway, I'll do it for you if you need. the solution has been given otherwise to make it work on Windows via Qt forum
so do you really want it?
this could be for v4.16 ;)

**Comment by Uukrull** [comment]
Since you already got a correct response from the QT forum and no workaround is needed, it doesn't really matter now :)

**Comment by mbruel** [comment]
ok thanks for your support :)
can you give it a try?
and confirm the problem is solved.
cheers

**Comment by Uukrull** [comment]
Yep. Compiled and working. Many thanks!

**Comment by clight77** [comment]
Hi
is there a help forum for this project?

Thanks
