### ISSUE TITLE
Is there a way to put files into a queue with a comand?

### ISSUE THREAD

**Issue by IITuxtmuxII** [mbruel/ngPost#122]
a bit like in a way like:
https://github.com/demanuel/NewsUP/wiki/Sharing-Torrents
this script does not put them into a queue, but posts it individually and only if the last one finished.
Is there a way to put them in a queue like with monitor?
regards,
Tux

**Comment by IITuxtmuxII** [comment]
I have tried it and it does not work like i wqant it I wanted a command that puts the folder not the files in that folder  in a queue for uploading and that this command can be used to put multiple folders in the queue.

**Comment by mbruel** [comment]
well just use a  script or a for loop with the path of your folders written in a file...
