### ISSUE TITLE
Posting in other groups

### ISSUE THREAD

**Issue by Minehors** [mbruel/ngPost#124]
alt.binaries.test,alt.binaries.misc,a2000.beeld.binaries,a.b.boneless

i have it like this and only the first group will be a singed to the indexers any way to fix this?

I run the latest version

**Comment by mbruel** [comment]
that's normal, you need to set up **GROUP_POLICY** to **ALL**
cf [README](https://github.com/mbruel/ngPost#configuration-file-and-keywords-that-are-only-in-config)
cf [conf](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L76)
```
## If you give several Groups (comma separated) you've 3 policy when posting:
##    ALL       : everything is posted on ALL the Groups
##    EACH_POST : each Post will be posted on a random Group from the list
##    EACH_FILE : each File will be posted on a random Group from the list (only with Article's obfuscation)
GROUP_POLICY = EACH_POST
```
