### ISSUE TITLE
[Mac OS] par2 not available on 4.16?

### ISSUE THREAD

**Issue by Cubbie3508** [mbruel/ngPost#126]
I'm having an issue with not being able to find par2 on 4.16.  This was not the case for 4.14.  Is there anything I need to set in .ngPost?  Any one else seeing similar issue?

<a href="https://imgur.com/nvDQMnJ"><img src="https://i.imgur.com/nvDQMnJ.png" title="source: imgur.com" /></a>

**Comment by mbruel** [comment]
Well it's inside the dmg
```
/tmp/ngPost/ngPost.app/Contents/MacOS$ ll
total 32M
drwx------ 2 bruel bruel 4.0K Nov 20 19:11 .
drwx------ 6 bruel bruel 4.0K Nov 20 19:11 ..
-rw-r--r-- 1 bruel bruel  35K Nov 20 19:09 LICENSE
-rw-r--r-- 1 bruel bruel 1.6M Nov 20 19:11 ngPost
-rw-r--r-- 1 bruel bruel 496K Nov 20 19:09 par2
-rw-r--r-- 1 bruel bruel  30M Nov 20 19:09 parpar

```
If you wish to use the one provided in the package you should let `PAR2_PATH` commented in the config file (`~/.ngPost`)
I guess that is what you have?

**Comment by Cubbie3508** [comment]
@mbruel yes it's commented out by default in .ngPost file but still can't find par2.  Worked fine with 4.14 and started not working with 4.15 and above.

Cheers.

<a href="https://imgur.com/OtMiCWi"><img src="https://i.imgur.com/OtMiCWi.png" title="source: imgur.com" /></a>

**Comment by l0co666** [comment]
Yes, works fine with 4.14 for me on M1 Mac, but not with 4.15 or 4.16...

**Comment by Uukrull** [comment]
PAR2_PATH should be:

`PAR2_PATH = /Applications/ngPost.app/Contents/MacOS/parpar`

with the correct PAR2_ARGS

**Comment by mbruel** [comment]
@l0co666, @Cubbie3508 
Indeed, this should work and use `parpar` which is faster. you could put `par2` if you would rather use that one.
But it is strange, it should work without defining `PAR2_PATH` like in the version 4.14. I didn't change anything except adding the LICENCE in that folder.
Can you tell the content of `/Applications/ngPost.app/Contents/MacOS/`
Thanks @Uukrull ;)

**Comment by l0co666** [comment]
Content from Folder MacOS are 3 files:

> ngpost
> par2
> parpar

**Comment by Uukrull** [comment]
Yes, that seems the problem. Version 4.14 was fine:

![image](https://user-images.githubusercontent.com/5891591/158037403-bb168d09-5320-4bbe-9969-56a9a62a4ae4.png)

**Comment by mbruel** [comment]
ok sorry for that, I've rebuilt a new VM with BigSur and didn't pay attention to the rights...
I'll change that for the next release

**Comment by mbruel** [comment]
I've built a [v4.16.1](https://github.com/mbruel/ngPost/releases/download/v4.16/ngPost_v4.16.1.dmg) with the rights corrected for future install ;)
