### ISSUE TITLE
Superposition de processus

### ISSUE THREAD

**Issue by Gigablu** [mbruel/ngPost#129]
Bonjour,

Serait-il possible d'empêcher qu'un processus PAR2 ne se superpose avec un processus RAR ou pire, avec un autre processus PAR2 quand l'option PREPARE_PACKING est sur True ? Je suis sur Ubuntu 20.04 et j'ai remarqué que quand cela se produit ça ralentit considérablement le travail au point qu'il devient plus rapide de supprimer le PREPARE PACKING. Quand deux processus PAR2 se superposent le travail est quasiment bloqué.

============
Hello,

Would it be possible to prevent a PAR2 process from overlapping with a RAR process or worse, with another PAR2 process when the PREPARE_PACKING option is set to True? I am on Ubuntu 20.04 and have noticed that when this happens it slows down the work considerably to the point that it becomes faster to remove the PREPARE PACKING.
When two PAR2 processes overlap, the work is almost blocked.

Thank you.

**Comment by mbruel** [comment]
hum,
I answer in english if you don't mind.
well normally there is only one packing at a time. when PREPARE_PACKING is active, when you start posting, you prepare the packing of the next post. It should only be 1 external process at a time, either rar or par2. Never both at the same time.
Are you sure that you've seen a par2 process and rar process?
This could be a bug, but I really doubt it could happen. I'll have to dig the code.
Please make sure this is happening and it is not just only your server that slows down due to a high bandwidth upload in parallel with par2 which is quite resource demanding...

**Comment by Gigablu** [comment]
The problem arises when a post ends before the preparation of the next one is finished (which often happens when you have a very fast connection and heavy posts). Because the software begins the preparation of the third post, as if the first one was really in progress while it is only at the stage of the preparation.
The worst is when the second post is heavier than the third and its rar process ends before the second post's par2 process is finished. At this point, we end up with two par2 processes which almost crashes the system.

Otherwise, by the way, a big thanx to you for this software. He revolutionized the way I post. ;-)

**Comment by mbruel** [comment]
alright I'm going to investigate and fix this, you're right, this shouldn't happen.
Thanks for raising the issue ;)
I'm glad you like ngPost :)
if you don't mind, I'll let you test it and validate the fix as I'm not posting much and definitely not heavy files.
what OS do you use? Windows 64bit?

**Comment by Gigablu** [comment]
I installed the software on a Windows 10 64bit PC and an Ubuntu 20.04 64bit PC as well. However, it's essentially the Ubuntu PC that I use with ngPost because the Windows PC is on WIFI and is limited to 5mb/s.
Otherwise, no problem, I'll come back to tell you how ngPost works, I use it a lot, I'll have the opportunity to test it
.

And many thanks for your work and your kindness.

**Comment by Gigablu** [comment]
The changes you made have significantly improved the operation of the software. I tested with about twenty files of 3.8Go then a dozen files of approximately 5Go, there was no problem. However, I noticed that the sending speed was greatly increased.
Perhaps the superposition of RAR and PAR2 processes also slowed down the sending of messages and not only their preparation. You have done a very nice job! :+1: 
If you don't mind, I would still like to test with files of much larger sizes and especially of different sizes from each other. And I'll let you know how it went.

**Comment by mbruel** [comment]
Cool, good news. What upload rate do you achieve? with how many connection?
People manage to achieve 110MB/s on servers using like 200 connections.
Personally at home I'm around 35MB/s on 50 connections which is far than enough for me.
Yeah I let you some time to test, I'll think about releasing the new version next sometime next week.
I guess it's you, thanks for the contribution ;)

**Comment by Gigablu** [comment]
200 connections, I didn't even know it was possible! No, NewsXS only allows a maximum of 25 connections. The changes you made to ngPost not only increased the speed of preparing posts, but also their upload speed. And what's interesting is that these two speeds are now, on my Ubuntu PC, almost identical. It saves me a lot of time.
Before the changes, the speed was 13 to 17 MB/s and this with a very long preparation time between two posts. Now I go almost to the maximum of what my Wifi card allows, 24.6 to 24.9 MB/s.
Faster would do me no good since I would have to wait for the end of the preparation process and slower would waste my time. I could go faster with my Windows PC which has a much better microprocessor, but to take advantage of its power, it would have to be connected to the box by an ethernet cable. It is not practical.
So I'm very happy! My tests yesterday showed no faults. I'm so happy, that I decided to make my contribution recurring. It is deserved ! Si, si, si ! :-)

**Comment by mbruel** [comment]
Great, happy you're happy and thanks a lot for the support ;)
à l'occasion, envoie moi un mail (matthieu.bruel@gmail.com) pour me dire dans quelles communautés tu traines.
je vais release la v4.17 du coup. merci pour le test!
