### ISSUE TITLE
limit Upload speed (I know that it was requested in the past)

### ISSUE THREAD

**Issue by zuricarmi** [mbruel/ngPost#132]
This program CAN NOT work as is in any working place
ALL internet traffic is useless with it running for ALL computers.
So like any normal downloader there MUST be an option to limit the traffic so others can use the internet at the same time.

This issue is critical and not just an option!

using another program to limit this program is difficult at best and a wrong way to fix a problem that this program creates.
Thanks

**Comment by mbruel** [comment]
well I don't know if it's complicated or not to limit the speed of a soft on your OS. There should be simple options.
ngPost is designed to be fast. I won't limit it.
most people using it are happy with saturating the bandwidth, that's even why they use it.
don't use ngPost in shared internet places... it's made for you at home or on dedicated servers!

**Comment by zuricarmi** [comment]
Hi
I use it at my home but with dedicated server my total upload with my max available speed will take months
this will make all pcs in my home stop using the internet.
I understand the need for speed but a program that by design preventing all others using the internet is not good (by design )

**Comment by mbruel** [comment]
it depends on your audience...
clearly mine is servers only dedicated to Usenet, and community members that post occasionally. They can do it during the night or when they're not home. I've added a pause feature in case they need the bandwidth back...
You can't make everyone happy.
There are always solutions outside the perimeter of a soft. And of course there are alternatives also!

**Comment by zuricarmi** [comment]
This program as is needs not dedicated server it needs dedicated internet service.

Any way thanks

**Comment by mbruel** [comment]
well you could limit the bandwidth if you want by decreasing the number of NNTP connections. Just use 2 or 3 instead of 50 ;)
but yeah I really don't have time or interest in adding a bandwidth monitoring feature...

**Comment by mbruel** [comment]
I first designed ngPost to be a simple fast command line Usenet poster. I've added a GUI and extra feature to help occasionally posters but I don't have anymore free time to continue with extra feature my communities doesn't need ;) 
the project is open source (GPL), if people want to add such feature, I can help if needed.

**Comment by zuricarmi** [comment]
I understand
Thanks

**Comment by zuricarmi** [comment]
I will try using 1-2 connections
thanks
