### ISSUE TITLE
 error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by IITuxtmuxII** [mbruel/ngPost#133]
Hello I get this error and wanted to know if there would be an fix for that?

./ngPost_4.16.AppImage: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by mbruel** [comment]
https://askubuntu.com/questions/386281/error-while-loading-shared-libraries-libglu-so-1
