### ISSUE TITLE
[request] add option to select "server doesn't require login"

### ISSUE THREAD

**Issue by simonmoore1** [mbruel/ngPost#14]
hi

i upload via virgin media newsgroup server and a username + password is not required.

when leaving the username and password fields empty ( blank ) i get error authentication denied

is there an option to add where you can select "server doesn't require login" similar to camel powerpost or yEncBin

even though i am leaving the fields blank the virgin media server is not detecting it that way

**Comment by mbruel** [comment]
hum ok, I'll look into that, I didn't know there were some providers without login/pass.
Are you using linux? would you be able to do a telnet connection to the provider to make sure what are the exchanges?
I can explain you what to do. 
I guess on windows you could use telnet too or netcat maybe

**Comment by simonmoore1** [comment]
I’m a noob with what you suggested lol. 
The settings I use with yenc are

News.virginmedia.com
Port 119
Untick option of requires password 

My isp is Virgin media and they offer this service free as long as it’s fron your home connection if that’s any help to you

I am using Windows

**Comment by mbruel** [comment]
ok could you try this, it's easy.
Open a cmd.
Install telnet using this command: `pkgmgr/iu:"TelnetClient"`
close the cmd.
open a new one
write: `telnet news.virginmedia.com 119`
you should see:
`200 Welcome (fx29.am4)`
write `head <8d7229324b354d058218e273b223db9e@ngPost>`
Let me know the output
then you can write `quit`

**Comment by mbruel** [comment]
> I am using Windows

which version did you install 32bit or 64bit?
I've made a fix for that, I'd like to send you the exe so you could try and let me know if it's working.
cheers

**Comment by simonmoore1** [comment]
I’m using 64 bit

**Comment by simonmoore1** [comment]
Yes sure send it over

**Comment by mbruel** [comment]
[here it is](https://files.fm/u/jqmjrb7j), let me know if it is working.
If so, please close the issue.
So you just need to let the USER empty (not even a space, nothing)

**Comment by simonmoore1** [comment]
Do you have a way we can communicate easier I am interested in a project you may be able to assist with

**Comment by simonmoore1** [comment]
Issue resolved. I will close once you reply to last message and many thanks for the fix :)

**Comment by mbruel** [comment]
sure, my email is published at the bottom of the [README of the project](https://github.com/mbruel/ngPost#questions--issues--requests) but here you go: Matthieu.Bruel@gmail.com

You're welcome for the fix, was not much to do but I honestly didn't thought you could get a free access without any login/password. In France they stop doing it, I remember 10 years ago, one provider was giving access to binaries but only with 3 days retention... Now they stopped

**Comment by mbruel** [comment]
PS: I'm quite curious about that project.. .drop me an email ;)
