### ISSUE TITLE
Option to automatically post .nfo files uncompressed. 

### ISSUE THREAD

**Issue by smbrannon** [mbruel/ngPost#140]
An option to include uncompressed .nfo file along with the compressed and par'd files. Perhaps an option to exclude all files ending in .nfo from compression and paring?

**Comment by mbruel** [comment]
well nowadays we don't really post uncompressed nfo do we?... 
maybe if there are other people interested but I don't have much time to spend on ngPost nowadays..

**Comment by smbrannon** [comment]
I still post NFOs sometimes, but no problem.
