### ISSUE TITLE
Option to ignore system proxy settings in Windows

### ISSUE THREAD

**Issue by smbrannon** [mbruel/ngPost#141]
Win 10 21H2
ngPost v4.16 using your posted binaries

An option to ignore Window's proxy settings would be great. The only other option I see is to disable the proxy system-wide and reenable after done posting, which would affect all traffic. Not the best of options.

Thanks for your great program!

**Comment by smbrannon** [comment]
The proxy allows the traffic, but the SSL handshake fails. Disabling the proxy in Windows' Internet Options solves the problem.

**Comment by mbruel** [comment]
I think it's a firewall issue, if the traffic goes, there is no reason only the SSL handshake would not.
but I'm not a windows expert...

**Comment by smbrannon** [comment]
It's a certificate issue with the proxy. Thus, having an option to ignore proxy settings would fix this. Many apps in the Windows world have an "Ignore proxy settings" setting. But, if it isn't something you're familiar with it probably isn't worth your time.

Thank you anyways. :-)
