### ISSUE TITLE
libGL.so.1 not included in AppImage??

### ISSUE THREAD

**Issue by methanoid** [mbruel/ngPost#142]
I think I found this with older versions & may have reported before but not sure which version of ngPost I have 

It seems rather crazy to have to "apt-get install libgl1-mesa-glx" and add 325Mb for one file missed???

**Comment by mbruel** [comment]
I guess you're using it on a server?
if it the case and you don't need the GUI, just use the [CMD version](https://github.com/mbruel/ngPost/releases/download/v4.16/ngPost_v4.16_cmd-x86_64.AppImage) which should not need libGL ;)

**Comment by methanoid** [comment]
I am.. Damn you are quick (and helpful). Thanks

**Comment by mbruel** [comment]
I guess I can close this ticket then ;)
