### ISSUE TITLE
Continue to have issues with V4.16

### ISSUE THREAD

**Issue by AnythingOldSkewl** [mbruel/ngPost#155]
I'm continuing to have issues with the latest version 4.16 using both Linux and Windows version. Below screenshot is from my Linux Seedbox on Ubuntu 20.04 ngPost seems to have a problem with WinRAR. HOWEVER, this problem does not exist in V4.14. Also, I've mentioned this before, The AppImg files does not contain the Par2 program, OR WinZip

![ngPostErr](https://user-images.githubusercontent.com/42495993/197573483-2d181b4c-b51f-4900-85c1-f9900f8e7722.png)

**Comment by mbruel** [comment]
it's not **Winrar.exe** but **Rar.exe** that you should use... cf [here](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L180)
I've just checked, both par2 and parpar are in the appimage. you can extract it and check it yourself following [this link](https://superuser.com/questions/1301583/how-can-i-extract-files-from-an-appimage)...
I'm not going to include compressing tools, they're separate programs. For par2 it's different, they're GPL and I've asked the owner of parpar.
