### ISSUE TITLE
How to obfuscate poset subject (and files names) when not using compression

### ISSUE THREAD

**Issue by zuricarmi** [mbruel/ngPost#159]
Hi
in windows cmd  (using conf file or without) how can **I post a file without using compression** so the posted subject and files list in it will be  obfuscated?
I tried all settings that I know of and all the time the posted subject reveal the file name
thanks

**Comment by mbruel** [comment]
to post with obfuscation without compression you need to use:
	-x or --obfuscate  : obfuscate the subjects of the articles (CAREFUL you won't find your post if you lose the nzb file)
The names are visible in the nzb but they're not on Usenet
