### ISSUE TITLE
DO NOT SHOW TAB UNTILL IT'S TIME TO LOAD , ONE BY ONE instead of open all tabs at once , app crash with mass upload , thousands of folders . 

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ngPost#161]
Hello , can u please maKe the app with 2 more options please

1 - dont load or open any tabs until the previous one is done instead of making it queued ?

if POSIBLE PLEASE MAKE THE APP RUN 
DO NOT SHOW TAB UNTILL IT'S TIME TO LOAD , ONE BY ONE instead of open all tabs at once , app crash with mass upload , thousands of folders . 

10K Folders at once or even more

2 - in default quick post it would be more helpful to drop a bunch of files into the windows but with option to upload each file with single nzb for it's own not the whole pack together please , thanks.

THANKS IN ADVANCE.

**Comment by mbruel** [comment]
1 ngPost is not made to have more than 10 or 100 tabs... 
use command line or alternate strategy... not sur why you'd have thousands folders to post separately, it doesn't make sense to me...

2 you can just drag and drop stuff on the Auto Posting tab and you'll have an nzb per item...
