### ISSUE TITLE
Post files on multi groups at the same time ?

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ngPost#162]
Hello , how to post the files into multi groups at the same time ? 

I did add 10 groups but it's automated NGPOST will pick one group randomly , can we choose multi groups for each post ?

thanks.

**Comment by mbruel** [comment]
you can set the [GROUP_POLICY to ALL](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L76) to post on multiple groups.
then in cmd, you could have several config files with different set of groups and using a script changing randomly depending on the file you post...
There is no possibility to achieve it with the GUI...
Anyway groups are not really useful... only the nzb no?

**Comment by DEVUVO** [comment]
Thanks , it works now.
