### ISSUE TITLE
Option to disable posting to usenet

### ISSUE THREAD

**Issue by Sonic3R** [mbruel/ngPost#171]
Hi,

There's option for to not upload to usenet provider after creating archive and par files ?

I have a good VPS with good CPU/RAM where archiving and par-ing going fast, but upload speed is limited to 100 Mbps (yes, you read correctly).

I want to download those generated files locally (with FTP) and then post them (maybe with nyuu or ngpost if supports directly  without creating again rar+par) using my connection (which is almost 600 Mbps, better than VPS).

Can help me here ?

**Comment by mbruel** [comment]
ngpost is a poster... all the options have been added to make it easier for people and use only one soft for posting.
so no I won't disable posting lol
it's a bit a waste of bandwidth to download by ftp to then post on usenet. you could just let it run in background on the VPS...
