### ISSUE TITLE
Allow posting if provide folder with rar and par2 inside

### ISSUE THREAD

**Issue by Sonic3R** [mbruel/ngPost#172]
I have sometimes connection issues with home network or I close program while posting but temp folder remains intact (that one with rar and par2).

Would be nice when drop folder (that one that contains encrypted rars and par2) in UI, I want to post directly but seems is not possible (I disabled compression and par2 generating):

![image](https://github.com/mbruel/ngPost/assets/6311947/e284413b-6ffc-413d-8744-90c6fa7805b4)

Btw, generating par on my machine take too much, I have slow PC, I don't want to re-create rar and par again. Would be nice to post directly (skipping compression and par2)

**Comment by mbruel** [comment]
just put all the the file included in the folder... 
I'm not sure I understand your problem :$

**Comment by Sonic3R** [comment]
I want to post directly to Usenet without creating other archive or create par from beginning

**Comment by mbruel** [comment]
yes that is what it will do on your snapshot. (unchecking compress, gen par2...)
just don't put a folder, put directly the file that are inside.
you can't post a folder without compression... you can only post files.

**Comment by mbruel** [comment]
easy, this should do the job: `ngpost -i /path/to/your/directory`
