### ISSUE TITLE
Inconsistency between readme and program

### ISSUE THREAD

**Issue by methanoid** [mbruel/ngPost#174]
the readme.md says "--auto_compress" but v4.16 says "Error syntax: Unknown option 'auto_compress' " so one is wrong???

PS: If I have a folder (/post) of subfolders and want to post each subfolder as a separate NZB what command please? 
ngpost --auto "/mnt/post" --compress --gen_name --gen_pass --gen_par2 -g alt.binaries.test 2>&1  | tee ngPost.$(date +"%Y.%m.%d-%H.%M.%S").log
???

**Comment by mbruel** [comment]
yes sorry it is quite outdated...
`--auto` is a keyword used for directories (parse directory and post every file/folder separately. You must use --compress, should add --gen_par2, --gen_name and --gen_pass)
`--auto_compress` is deprecated: obsolete keyword AUTO_COMPRESS, you should use PACK instead, please refer to the [conf example](https://github.com/mbruel/ngPost/blob/master/ngPost.conf#L149)

so you could do `ngpost --pack --auto /mnt/post ` having in the conf `PACK = COMPRESS, GEN_NAME, GEN_PASS, GEN_PAR2
it will do the same thing than `ngpost --compress --gen_name --gen_pass --gen_par2 --auto /mnt/post`
