### ISSUE TITLE
Portable Windows version

### ISSUE THREAD

**Issue by zooool** [mbruel/ngPost#176]
> you don't need administration rights to install. the setup is just a packaging.
> you can zip yourself the folder and use it on another computer.
> easy DIY ;)

That's not true. You are only offering a .exe setup for Windows. You need to be offering a .zip so people can just extract the files and run the program without having to install anything or without having to change the registry.

**Comment by mbruel** [comment]
I'm not sure what does the packing software (InnoSetup) in the registry, yeah probably just write the version of the installed version. Normally it shouldn't ask for any admin rights if you install on the desktop our your user environment.
Well you can just do the portable version yourself. I don't have to provide all the formats... most people find the installer easier...
As I told you, just ask some that has the same architecture (32 or 64) to make you a zip file of the installed folder. Or do it yourself then uninstall ngPost. There won't be any trace left on your system!
