### ISSUE TITLE
[HELP] Would GROUP_POLICY work without config?

### ISSUE THREAD

**Issue by j0hnckuy** [mbruel/ngPost#179]
I'm using commandline and without reference to the .config file. Would -g still work for a folder with multiple files? Would articles get posted in different groups? In other words, would GROUP_POLICY work without a config file?

Command I am using: 

`-g "alt.binaries.teevee,alt.binaries.danskefilm,alt.binaries.french,alt.binaries.etc"`

**Comment by mbruel** [comment]
well just give it a try...
without any config, the default `GROUP_POLICY` is `GROUP_POLICY::ALL` (you can see it [here](https://github.com/mbruel/ngPost/blob/7f4762b66ceefb5016a9fa6cefd310e0d3da6936/src/NgPost.cpp#L301))

**Comment by j0hnckuy** [comment]
Sorry, that got me confused there.

so ALL means that every file will be uploaded in every group or what? I think i missed something. I want EACH_FILE how should I proceed. Can you give me an example of config file and how to import it in CMD line to use it. Please.
