### ISSUE TITLE
[Poster #1 {NntpCon #4}] Error SSL Socket: - The host name did not match any of the valid hosts for this certificate

### ISSUE THREAD

**Issue by wafranyofl** [mbruel/ngPost#182]
Hello! I get the following error message when trying to post something with ngpost 4.16 for Windows. I configured everything in ngpost.config as I understood it. At last I filled in username, password and port using copy & paste. While I can successfully use these e.g. in JBinDown ngpost gives the following error messages over and over:

[Poster #1 {NntpCon #4}] Error SSL Socket: - The host name did not match any of the valid hosts for this certificate 

[Poster #1 {NntpCon #3}] Verbindung verloren, versuche wiederherzustellen! (nb getrennt: 1)

I don't know how to solve this. Why can JBinUp download and post with the same credentials and ngpost can't? Seems to be an SSL issue but I can't handle it.

Windows 10 Pro / ngpost 4.16 / server: dreamload / port: 563

**Comment by BakasuraRCE** [comment]
You probably have OpenSSL version 3.x, you should change it to 1.x for it to work.

**Comment by BakasuraRCE** [comment]
Here is a simple fix to get working without change openssl system version:

1. Compile openssl
```bash
wget https://www.openssl.org/source/openssl-1.1.1v.tar.gz
tar -zxf openssl-1.1.1v.tar.gz && cd openssl-1.1.1v
./config
make
make test
```
2. Move .so files inclusing symlinks to your custom lib dir `mv *.so* /custom/dir/lib`
3. Wrap the AppImage in bash
```bash
#!/bin/bash

set -e

script_path="$(cd "$(dirname "$0")" && pwd)"

# change openssl by 1.1.x
export LD_LIBRARY_PATH=${script_path}/lib:$LD_LIBRARY_PATH
# run NgPost
"${script_path}/ngPost_v4.16_cmd-x86_64.AppImage" "$@"
```
4. Run `/wrap.sh param1 param2 ...`

**Comment by wafranyofl** [comment]
Thank you for your answer.

>Here is a simple fix to get working without change openssl system version:
>
>1. Compile openssl
>```bash
[...]

I don't want to change to openssl 1.0 because of its security flaws.
And for your compiling instructions: it's all greek to me. I'm a user,
not a programmer. Meanwhile I'm trying out PostCommander where I can
skip the verification of the SSL certificate. Works for me though I
like the GUI of ngPost better.

Best wishes
Detlef Wirsing



>wget https://www.openssl.org/source/openssl-1.1.1v.tar.gz
>tar -zxf openssl-1.1.1v.tar.gz && cd openssl-1.1.1v
>./config
>make
>make test
>```
>2. Move .so files inclusing symlinks to your custom lib dir `mv *.so* /custom/dir/lib`
>3. Wrap the AppImage in bash
>```bash
>#!/bin/bash
>
>set -e
>
>script_path="$(cd "$(dirname "$0")" && pwd)"
>
># change openssl by 1.1.x
>export LD_LIBRARY_PATH=${script_path}/lib:$LD_LIBRARY_PATH
># run NgPost
>"${script_path}/ngPost_v4.16_cmd-x86_64.AppImage" "$@"
>```
>4. Run `/wrap.sh param1 param2 ...`

**Comment by CevreMuhendisi** [comment]
Change your provider

**Comment by mbruel** [comment]
well, I have a life, ngPpost is not at all a priority especially mainstream for non issues but just lazy confort... 
anyway, I should soon make a new versionwith Qt 6, it will use openssl 3, I hope it will handle directly the older versions... it should... I'll make some tests...
