### ISSUE TITLE
Fails at terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by alfablac** [mbruel/ngPost#184]
Getting this after parpar

*****************
Processing time   : 3.291 s

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

Can't pinpoint where the error is. Running the parpar command I get 100% processed, so I guess that is on ngPost.

**Comment by alfablac** [comment]
After some testing I was not able to find a solution
It seems this problem is only triggered if I set two servers for posting
Once I add only one I can max all 50 connections. I'm not sure if it's a limitation on Debian on threads per proccess.
I don't know a server that allow more than 50 connections tho, so I can't exactly figure out if it's the two servers or is a  thread limitation.

**Comment by mbruel** [comment]
There shouldn't be any problem to support several servers.
The number of threads is limited to the max of your system. There is no benefit to use more. The app is event based and asynchrone, this is faster than threads.
I can't help with your crash. This could be a memory issue...
