### ISSUE TITLE
How does one add posts to categories on indexers?

### ISSUE THREAD

**Issue by King-0f-Hero** [mbruel/ngPost#188]
Excuse my lack of knowledge - I'm just starting out posting to Usenet and I've got a question to which I can't find an answer literally anywhere across websites, forums, subreddits and the indexers themselves and so I hoped to maybe get an answer here.
My problem is that I was posting several movies (of course only open-source ones...) to alt.binaries.boneless and can't figure out how categories on indexers work.
How and who (people or algorithms) selects which posts end up in which categories?

With tests I did beforehand with ngPost (with a trailer for one of these movies for a quicker upload to test out several settings) only one of them ended up in the intended subcategory of movies (only on one of the indexers I use - namely drunkenslug) maybe because I named them correspondingly ("3D" was included in the Title and file name so it ended up in  the Movies>3D category) but I've named all the other tests and actual posts/uploads similarly. And everything else I've tried (even by posting to alt.binaries.3d and alt.binaries.movies) ended up in other categories like TV>Other.
I want to make it easier to find these posts for other people who are searching for this specific kind of content and like I said - I couldn't find any resources or information about this topic out there. So can somebody here help me or at least point me to somewhere where I could educate myself further on this topic?

**Comment by mbruel** [comment]
This is not a question about ngPost...
ask on other forums or communities.
please not here!
