### ISSUE TITLE
Save NZB's with full the Full Path name for posted files and folders

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ngPost#189]
Hello , Please help me save the nzb File names with the full path if possible and if there is partial options for 2 parent folders that will be more helpful

So having same folders names will be overwritten , for example

I have 2 folders

C:\STUDIO\VIDEO\1000
C:\STUDIO\VOICE\1000

I want to be able to save 1000 folder with it's path name without the C:\

Thanks.

**Comment by DEVUVO** [comment]
If this is not possible can I post folders with timestamp ? or unique mark so it will not be overwritten ? some help please

**Comment by mbruel** [comment]
You can modify the name of the nzb by hand (if a quick post).
In any case, there is no overriding, if 1000.nzb exists, then 1000_1.nzb will be created, then 1000_2.nzb...
you can rename them once created if needed ;)

**Comment by DEVUVO** [comment]
I'm using autoPost and it keeps asking me if i want to overwriting 

there is no auto nzb will be generated with _1.nzb if so how to make it possible ?

**Comment by DEVUVO** [comment]
when I upload 2 folders having different files with the same folder names the NGPOST asking for replace the nzb , so it dont autosave , can you please help me here how to do the auto save with add _*.nzb ?

as you said earlier

there is no overriding, if 1000.nzb exists, then 1000_1.nzb will be created, then 1000_2.nzb...
