### ISSUE TITLE
[Request] Padding of subject #

### ISSUE THREAD

**Issue by AssRap3r** [mbruel/ngPost#19]
only a minor request and it's mostly just cosmetic

subject id's should have number padding to correct the sort order. when loading the nzb in something like alt.binz the order of the subjects is messed up because there's no padding on the numbers

example:
ngPost sorting:
![unsorted](https://user-images.githubusercontent.com/42024522/74414520-80d88f80-4e39-11ea-804a-859d59c47c28.PNG)
Nyuu sorting:
![sorted](https://user-images.githubusercontent.com/42024522/74414522-81712600-4e39-11ea-9748-1be2a983f36a.PNG)

**Comment by mbruel** [comment]
ok, done, this will be the v5.1 that should arrive tonight or tomorrow ;)
