### ISSUE TITLE
build 32bit please

### ISSUE THREAD

**Issue by ahmedtds** [mbruel/ngPost#2]
thanks

**Comment by mbruel** [comment]
ok, I'll add that soon with the next release (probably next weekend)

**Comment by mbruel** [comment]
I've added the new releases for both win32 and win64
I'm getting troubles to build linux releases due to libssl dependencies.. I'll check them when I'll have more time

**Comment by ahmedtds** [comment]
Thank you so much! win32 is enough for me.
I hate devs who only build 64bit because 64bit OS can run 32bit apps but 32bit OS can't run 64bit apps. So build only 32bit then instead of only 64bit if you are gonna build for only one arch because 32bit apps can be run by both but 64bit apps can only be run by one of them.
Anyway thank you so much for responding and caring about it.

**Comment by mbruel** [comment]
Well you're right, it makes sense to build a 32bit release rather than only a 64bit for small applications.
I'm just used to prefer 64bit due to memory limitations with 32bit apps

**Comment by mbruel** [comment]
Could you please close the issue ;)
