### ISSUE TITLE
Allow shutdown script to receive original path of upload and nzbfile.

### ISSUE THREAD

**Issue by r0x0r316** [mbruel/ngPost#20]
for instance like sabnzbd does for its processing and preprocessing scripts $1 for the full path of the upload and $2 for the resulting nzb file $3 for the rarname and $4 for the password used. this would allow further postprocessing of the upload for archiving into a cloud for instance or gathering information on the nature of the upload like mediainfo and so on.

**Comment by mbruel** [comment]
Hi,
The shutdown script is not a post processing script. It's not scheduled at the end of each post, just at the end of the queue for people that basically schedule 50 posts overnight.
Pre and Post processing scripts could be introduced, but for me that would be another keyword.

**Comment by r0x0r316** [comment]
True i did get the wrong impression thx for the clarification. :D So pre post processing would be nice. For instance make screenshots from videos and so on could be easily integrated then.

**Comment by mbruel** [comment]
I'm closing this issue.
Open a new Request thread for the pre post script but I won't really have time to do it in the coming months
