### ISSUE TITLE
Autoposting: all files in monitored folder with same password?

### ISSUE THREAD

**Issue by Lieferschein** [mbruel/ngPost#205]
I was wondering if this is intentional, since there is a "generate random password" option on the bottom of the UI.

It seems, that all the NZBs from the files will have the same password, which kind of defeats the purpose. The poster email is random, the filename of the RAR is random, but not the password.
Maybe that option is not working for me (v 4.16), or am I misunderstanding this option?

**Comment by Lieferschein** [comment]
Sure:
https://i.ibb.co/hZqyhw0/ng1.jpg
https://i.ibb.co/mSvm4b9/ng2.jpg
https://i.ibb.co/JrykdH9/ng3.jpg

These are a few of the NZBs generated by the dummy upload: https://i.ibb.co/JBNvNq8/ng4.jpg

There's a second issue/question regarding passwords: when I change the "archive password" (top of the UI), the "nzb password" (bottom) will change accordingly. I will then have to change the nzb pw manually, to get a different one from the archive pw. Is this also a malfunction?

**Comment by mbruel** [comment]
If you've `archived password checked on the top right, it is overtaking the auto password generation.
So just untick this and you should be fine.
Please confirm.
Cheers

**Comment by Lieferschein** [comment]
> If you've `archived password checked on the top right, it is overtaking the auto password generation. So just untick this and you should be fine. Please confirm. Cheers

It works exactly as you say now. Thanks! I wasn't aware of that and thought, just like using the Quick Post option, the pw would still be generated randomly for each post.

**Comment by mbruel** [comment]
I think the behaviour for quickpost is the same but I can be wrong... I don't remember but it would make sense.
A bit everywhere I've added tooltips. If you go other the checkbox or the text `archive password` you can see the following: **Use a fixed password for all the posts**
I took some time to add Tooltips, so please check before asking questions or opening a bug.
I know the GUI is quite minimal, but I never had the intention to do one...
I did it bits after bits to help the community ;)
I may open a crowdfounding for the v5 to create a more modern one ;)

**Comment by Lieferschein** [comment]
> I think the behaviour for quickpost is the same but I can be wrong... I don't remember but it would make sense. A bit everywhere I've added tooltips. If you go other the checkbox or the text `archive password` you can see the following: **Use a fixed password for all the posts** I took some time to add Tooltips, so please check before asking questions or opening a bug. 

I appreciate your work and am grateful for a UI :) I always check the tool tips. And in this case I was a bit confused, for 1. it says "NZB" pw at the bottom, but "ARCHIVE" pw at the top - but it means the same thing? And 2. for some reason it worked for me that way - each time I open a tab for a Quick Post, I get a different random pw if "ARCHIVE" pw is unchecked, but NZB pw is checked..

**Comment by mbruel** [comment]
ok that must be a bug.
basically archive password is the password you will add in the nzb header. (meta section)
some people could do a quickpost with archives they have generated or get from another source and that has a password. Do you see the difference?
nzb password, means that you want to package your post with a password, that one. (except the one from the top is supposed to be used for those that want to use all the time the same password.
Am I clear about the difference?

**Comment by Lieferschein** [comment]
> Am I clear about the difference?

Okay, now I get it. Is that explained anywhere? Maybe I didn't completely read it.
Maybe if they used the same term, (or maybe you can add it in in the tool tip in future updates?), it would have been clearer to me.
btw: Here is what happens to the PW when I click new quick post, when "Archive PW" is disabled: https://imgur.com/nisPN2I
Thanks!

**Comment by mbruel** [comment]
well man Usenet used to be for people with a minimum of IT or computer science background...
It wasn't mainstream at all.
no need of obfuscation. majors didn't claim DMCA requests...
I can' explain everything... for me it is obvious and documentation is in general the worst part of a dev job...
well no worries, you can ask questions. Maybe better to do it on the Discord channel than here as an Issue that is not really an issue.
[Here is an invite for the brand new discord server](https://discord.gg/TwYRDy9), feel free to join if you've questions or if interested in beta testing the new features before they're released ;)

**Comment by Lieferschein** [comment]
Appreciated!
