### ISSUE TITLE
So much missing connection cause incomplete upload 

### ISSUE THREAD

**Issue by Zach99f** [mbruel/ngPost#213]
Hello, where's the mbruel guy he need to help us fix these issues 

Using quick post or regular post both give me many missing connections if upload anything small posts in sizes or if uploading more than 80 posts , i tested my connection with other upload tools no problem at all . This is happening with making random names or even preset files without changing the apps settings, used more than one provider to test it is the ngpost nothing else any idea please help. Thank you

**Comment by mbruel** [comment]
Use not all the connections just in case. if your provider allows 50, use just 40, the upload rate won't drop.
otherwise nothing to do with the way to post.
could have been an issue of the provider..

**Comment by Zach99f** [comment]
This is weird, I used 20 threads and 20 connections , it worked, any other settings will cause drops.
