### ISSUE TITLE
[Feature Request] Allow accented characters in nzb output

### ISSUE THREAD

**Issue by AssRap3r** [mbruel/ngPost#22]
another small request - accented characters are replaced on the output nzb filename which can break posting scripts, preferably they should be kept intact and not replaced

**Comment by mbruel** [comment]
I introduce this removal cause some people asked for it. That's true, I should let the choice to the users.
I've pushed a fix with the introduction of a new keyword in the config file.
`
commit 1844c253e801131e9d90d43119515e6f98d81680 (HEAD -> master, origin/master, origin/HEAD)
Author: Matthieu Bruel <Matthieu.Bruel@gmail.com>
Date:   Sat Mar 7 17:15:28 2020 +0100

    issue #22 : introduce keyword NZB_RM_ACCENTS in conf file to remove special characters instead of doing it by default
`
Are you able to compile yourself? what OS do you use? I'm not going to make new releases just with this small change.

So by default, with the current config, the removal of the special chars is off. To activate it, you need to uncomment in the config file:
`
## remove accents and special characters from the nzb file names
#NZB_RM_ACCENTS = true
`

**Comment by AssRap3r** [comment]
tested and working  it's not a critical change so I can wait until the next version is released, no rush on this specific issue

**Comment by mbruel** [comment]
ok, I close it then ;)
