### ISSUE TITLE
[Request] Progress timestamps

### ISSUE THREAD

**Issue by kDipak** [mbruel/ngPost#28]
Hello There,

can you add some sort of timestamps to the command line outputs.  I tried -d switch but it doesn't do any timestamps :)

I am sometimes running into the issue that a post is going fine but the speed suddenly drops and it stops progressing altogether, it stops sending packets but won't throw an error of a time-out or anything.

Only way to resolve is to stop the command line with a break (ctrl+c). preferably timestamp output when using the --disp_progress FILES. 

For example the time it started processing a package and when it ended.

**Comment by mbruel** [comment]
I've added the timestamp for the command line ;)

**Comment by mbruel** [comment]
[here is a compiled version for win64 ](https://files.fm/u/wwsjhghk) if you want to try before the next release ;)
