### ISSUE TITLE
[Request] Option to enable/disable servers without removing them from conf

### ISSUE THREAD

**Issue by kDipak** [mbruel/ngPost#30]
Hello Matthieu :)

Is it possible to add the option to enable/disable servers. in the GUI ? current options is you have to use all of remove what you don't want to use.

I can disable it in the conf file by commenting them out, but when i open and change a setting in the GUI, it overwrites and removes the commented servers.

**Comment by mbruel** [comment]
Hi Dipak,
I've added it.
Thanks for the donation ;)
Here is a [win64 build](https://files.fm/u/654t5ndw).
I'll probably have some time during those confinement time, I may release the new version v4.5 in April.
Let me know if you find a bug, otherwise, please close the issue.
Cheers!

**Comment by kDipak** [comment]
Thanks 👍 for adding it to the GUI. 

the command line is ignoring it and using all servers :)

**Comment by mbruel** [comment]
Indeed I went to fast and only focussed on the GUI...
[Try this version](https://files.fm/u/3chv2338), it should work for both cmd and GUI. (didn't test it but I'm quite confident)
Please close the issue if it's working as expected.
Cheers

**Comment by kDipak** [comment]
Tested and working as intended in the cmdline version.

thank you.
