### ISSUE TITLE
!! Request !! Important features .

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ngPost#31]
Please add an option for random poster email name on each upload / file or folder

add a default password on automatic option or a random rar names on the quick option 

close each tab after its done correctly uploaded , ( green mark )

Option to control the cpu usage , such as if you are using auto mode and leave the pc on , it will not effect the other running app , the cpu for the par can take up to 67 and up while creating pars

thanks , hope to see this happened.

**Comment by mbruel** [comment]
> Please add an option for random poster email name on each upload / file or folder

this as been done and published. it will be available on the next release or it's in [this version for win64](https://files.fm/u/3chv2338) if you wish. (just replace the exe in the ngPost installation folder)

> add a default password on automatic option or a random rar names on the quick option

This is to avoid 4 clicks? well it can be done...

> close each tab after its done correctly uploaded , ( green mark )

I'll probably add this in the next release.


> Option to control the cpu usage , such as if you are using auto mode and leave the pc on , it will not effect the other running app , the cpu for the par can take up to 67 and up while creating pars

ngPost doesn't use much CPU I think. As you said, par2 does. It's advised to use [ParPar](https://github.com/animetosho/ParPar) to generate the par2. You can set the number of threads in the parameters:
```
PAR2_PATH = <your path to>/Parpar.exe

PAR2_ARGS = -s5M -r1n*0.6 -m2048M -p1l -t4 --progress stdout -q
```

That the -t4 option. Reduce the number of threads. You can put half what you've for example...

Please consider to [make a donation](https://github.com/mbruel/ngPost#donations) to reward the support and motivate me to find some time to make your requests happen ;)

**Comment by DEVUVO** [comment]
As i am backing my training videos on usenet I only have windows 64 I don't know how to use parpar with this code i dont use linux and i am not good on command line either sorry!

Can you make an option for that to be easy for me as a windows user maybe option for parpar with gui limits such as what in multipar

here is my 2 screenshot it might help

I just send you a few bucks and more will come when i can .

you are awesome , thank you , i will test the new exe u sent and will report if any issues .

the project is going to be the one and only perfect usenet poster ever , we need to keep it up , thanks for your time .

**Comment by mbruel** [comment]
> As i am backing my training videos on usenet I only have windows 64 I don't know how to use parpar with this code i dont use linux and i am not good on command line either sorry!

ParPar binary for win64 is available on GitHub. [It's here](https://github.com/animetosho/ParPar/releases/download/v0.3.1/parpar.v0.3.1.win64.7z).
unzip (with 7zip), put it wherever, you can put it in ngPost folder. Then edit ngPost.conf to set that:
```
PAR2_PATH = C:\ngPost\parpar.exe

PAR2_ARGS = -s5M -r1n*0.6 -m2048M -p1l --progress stdout -q
```
You'll see the perf are muuuuuch better!



> here is my 2 screenshot it might help

where are they?


Thanks for your contribution and the congratulations :)
I'm working on it this afternoon, I'm going to add few handy new features ;)

**Comment by DEVUVO** [comment]
```
https://ibb.co/RNzBt34
https://ibb.co/VBTRRcM
```
thanks for the reply . oh sorry i dont know why links wasnt inserted earlier but anyway
here is the 2 screen , if we can get it done like this will save time too , thank you.

**Comment by mbruel** [comment]
> ```
> https://ibb.co/RNzBt34
> https://ibb.co/VBTRRcM
> ```
> 
> thanks for the reply . oh sorry i dont know why links wasnt inserted earlier but anyway
> here is the 2 screen , if we can get it done like this will save time too , thank you.

As I said, I won't do anything for regulate the CPU usage. If you want to do it, just use ParPar or Multipar and add the relevant ARGS in the config file. EASY. No need to do command line. I gave you what to do with ParPar.

Most features are implemented, here is a version for win64, let me know what you think.
Replace the exe, run, you'll see the new stuff in the parameters section.

**Comment by DEVUVO** [comment]
I tried to edit the config file but the app closes by it self and some line has # front of it i might editing something wrong , and also i dont have choice over how many % of the redundancy i needs to control it if possible please

can you please edit the config file yourself and send it please , i am confused i know its easy but not for me.

**Comment by DEVUVO** [comment]
Ok , i think i got it to work but now what if i want 20 % of pars instead of auto 10 % ?

any idea ? thanks man everything else works great.

**Comment by mbruel** [comment]
You can't choose the redundancy percentage when using a custom par2 generator other than par2cmdline. It will be fix and define in the config file within PAR2_ARGS.
I'll probably work on that for the next version.
I'm closing this issue. Feel free to open another request for that.
Cheers
