### ISSUE TITLE
Out of memory: killed process

### ISSUE THREAD

**Issue by DarkShadowxx** [mbruel/ngPost#33]
Hello,

I am trying to upload a backup with 250 GB right now.
But after a couple of hours (around 70%), ngpost seems to use all the available RAM (the vm has 20 GB). When trying to login, the ngPost process gets killed, because the system has way too little RAM left.

What should I do?

**Comment by mbruel** [comment]
hum...
ngPost shouldn't use much memory.  it is releasing file by file...
Are you posting 1 big file of 250 GB? oO or is it split?

**Usenet shouldn't be used for personal Backup... It's a sharing network...**

**Comment by DarkShadowxx** [comment]
It is split in rars with 200 MB each.
But I just noticed that the generated par2 files have increasing sizes, the biggest is >30 GB (using parpar)!

Is there a way to limit the size of each par2 file?

**Comment by AssRap3r** [comment]
@DarkShadowxx parpar defaults to pow2. you need to change it to -duniform -p<#/%>, where #/% is replaced with either the amount of slices per par2 file, or a percentage of the overall recovery record 

example:
4.3GB file split into 50MB, par to 10%

-dpow2 will give you 10 increasing size par2 files (783KB ~ 157MB / 1~256 blocks per par2)
-duniform -p1% will give you 11 equally sized par2 files (40.7MB / 64~65 blocks per par2)
-dpow2 -p1% will give you 16 increasing size par2 files (783KB ~ 44.3MB / 1~71 blocks per par2)

try the commands separate from ngPost at first and then add them once you've found the right balance

**Comment by AssRap3r** [comment]
@mbruel ran into this problem today too. uploading a 1.9GB file and both times it cut out at the same place - 2691/2745 articles posted (1,883,700 KB). shut down sabnzbd to free some memory, turned on debugging and was able to get it to successfully upload on the third try.

**Comment by mbruel** [comment]
Well that's strange but I'm going to dig into it and check the memory usage.

1.: what is your machine? what OS, what CPU (or how many cores), how many GB of RAM?
2.: Do you run command line or with the GUI?
3.: I'll try to post a 2GB file to track the memory. What were your exact parameters? Did you compress? what size of the rar? what is your PAR2_ARGS?


> both times it was killed at the same place - 2691/2745 articles posted (1,883,700 KB).

what do you mean it was killed? what error did you have?


> CPU usage was about 68% and memory 75%

only by ngPost or the whole system?

**Comment by AssRap3r** [comment]
Ubuntu 16.04.6 LTS, 8 cores, 2GB ram/4GB swap
Command line
ngPost -o out.nzb -i folder (config set to use 8 threads + 20 connections)

rar/par was done separately - ngPost was just used to upload it. It wasn't just a 1.9GB file - there were others preceding it, but that was the file it died on twice. the final (broken) nzbs were 3.792,874 KB

nzb:
![image](https://user-images.githubusercontent.com/42024522/79040906-ca4c1d80-7be3-11ea-85d7-8ed9a5751227.png)

All files:
![image](https://user-images.githubusercontent.com/42024522/79040744-a3411c00-7be2-11ea-82c7-aedacffc3571.png)

both times the message was Killed. after shutting down sab, logging to a file & then trying again it was successful. CPU/MEM usage was for ngPost.

**Comment by mbruel** [comment]
arf... 4GB par2 file... oO
well I may have a lead. Apparently I'm not freeing properly the Articles, as std::string clear is not doing it.
do you compile from the sources?
I'm going to change this behaviour. Maybe do a special version for you with extra debug on Construction / Destruction of the Objects.

**Comment by AssRap3r** [comment]
yes, i compile from the git source but can run pre-compiled debug versions if needed. my normal pars aren't this big (this was for something already on usenet) which is why it hasn't come up before

**Comment by mbruel** [comment]
I've pushed a "major change" on the way I manage the memory of the Articles.
it should solve the issue. I can't guarantee but I'm quite confident. I thought a clear on std::string would release memory but apparently it doesn't. I'm now using C style char * on the heap that I delete.
Do you still have you post that was crashing? Could you give it a try? Is it using less memory? still crashing?

**Comment by AssRap3r** [comment]
just compiled and tried the same files, no crashes and memory usage is hugely reduced:

57.4% CPU /   8.8% MEM

**Comment by mbruel** [comment]
cool then I guess I can close the issue right?
In term of upload speed, have you notice a difference? in good or bad?

**Comment by AssRap3r** [comment]
@mbruel around 75MB/s seems to be the new normal, other times it would between 40-70MB/s (but could just be down to the time of day, the box & link speed is shared)

```
[16:24:00.177] Upload size: 5.49 GB in 00:02:07.269 (127 sec)
 average speed:  44.19 MB/s (20 connections on 8 threads)

[16:24:04.507] Upload size: 5.71 GB in 00:02:08.177 (128 sec) 
 average speed:  45.60 MB/s (20 connections on 8 threads)

[16:27:49.264] Upload size: 4.42 GB in 00:00:59.073 (59 sec)
 average speed:  76.69 MB/s (20 connections on 8 threads)

[16:32:02.870] Upload size: 5.17 GB in 00:01:04.779 (64 sec)
 average speed:  81.67 MB/s (20 connections on 8 threads)

[16:35:43.395] Upload size: 4.69 GB in 00:01:03.520 (63 sec)
 average speed:  75.64 MB/s (20 connections on 8 threads)
```

the first two were running concurrently which is why they're ~45Mb/s, the others were sequential. if I increase the connections I can hit 100Mb/s which is the maximum speed of my box; so absolutely no complaints about speed. 
```
[16:39:30.566] Upload size: 4.94 GB in 00:00:50.111 (50 sec) 
average speed: 100.88 MB/s (40 connections on 8 threads)
```
