### ISSUE TITLE
Auto Compress + top Archive password not working properly

### ISSUE THREAD

**Issue by DEVUVO** [mbruel/ngPost#35]
Hello , there is small issues that Auto compress for quickposts and random archive name and par don't work so what is the reason for it if we select it ? without selecting all lower choices and tick each one of them

if i select a single file or 2 file parts with same names
aaa.rar
aaa.r00
or 
2 different files
111.rar
222.rar

it will still pickup one name of the files name nothing random  i can't make it to be random unless i click generate or write my own

same thing with nzb passwords it said fixed pass for all posts , this is not working for all posts it will only pick up a fixed password for quickposts no matter the archive password on top is ticked or not , if i tick the top archive password and have a fixed pass and put a fixed pass on the lower option the app will only pick up the lower option , the top pass only works with auto posting

i guess if you can fix the auto compress to work for the quickpost it will fix all this issues

also if the auto compress if enable could disable the option on the lower panel this will help without removing the lower option , just when you choose one option it disable the other option automatically till you change it again or do it manual when disable the auto compress

i dont know how to be more accurate explaining this but if you tried it while posting you will see , this is what i find so far .

thank you .

**Comment by mbruel** [comment]
Hi,
For auto compress, auto close and archive password, you need to SAVE. Close
the APP and relaunch.
Those are "static configs" that are loaded from the config file. It doesn't
modify live the Quick Posts.
I believe it is working as expected once you know that no?

**Comment by mbruel** [comment]
I've made the changes to update dynamically the GUI.
Here is [the latest build](https://files.fm/f/c4t7dtfy). It might be the v4.5 that I'll release tonight or tomorrow.
I'm waiting on your feedbacks.
Let me know if you find a bug.
Cheers

**Comment by DEVUVO** [comment]
The app works fine after save the setting and close and reopen yes , the only last thing i can think of is the percentage of the par2 , how about if i want to create 50 % pars or more or less i know it's a lot but that's what i do sometimes just in case , everything else works as it should. will close this issue so others will know .
