### ISSUE TITLE
New install overwrites ngPost.conf file and old 4.3 exe installed

### ISSUE THREAD

**Issue by kDipak** [mbruel/ngPost#36]
Hello Matthieu, 

I just downloaded the 4.4. release and installed it in the old directory. 
It replaced ngPost.conf with a default one, can this not be the default action ? (luckily i made a back-up just before installing)

i donwloaded the the 64bit installer and the ngpost.exe file it installs is from feb 18 2020. seems to be missing all the modifications.

**Comment by mbruel** [comment]
I never do a second version of a release. I always increase the version number. So normally the installation folder should be different and you can copy the conf of the previous one (and then uninstall that previous version).

Between two releases, I'm building only the ngPost.exe binary (for win64) so people can validate a fix. You should just overwrite the executable in your installation folder.
So if you want to try, [here is the latest one](https://files.fm/f/c4t7dtfy) with all the new features.
But the v4.5 should arrive today or tomorrow ;)

Have a good day!
