### ISSUE TITLE
[REQUEST] Support for subdirectories

### ISSUE THREAD

**Issue by Einhuman197** [mbruel/ngPost#39]
Love using ngPost, but I have one suggestion.

When posting some scene releases they have subfolders in their natural file structure (like Sample Folders and Subs Folders). These don't work when posting, I have to modify the file structure for that. So implementation of Sub-directory handling would be great.

Thanks in advance.

**Comment by mbruel** [comment]
Hi,
if you want to keep the structure, you should post the root folder containing the movie and the subfolders (Sample and Subs) using compression. It will be recursive and contain everything.
There are no other ways to keep the structure.
