### ISSUE TITLE
Command line -f option doesn't work

### ISSUE THREAD

**Issue by Uukrull** [mbruel/ngPost#4]
The uploader can't be set with, for example, -f someone@nobody.com and it looks that the code is missing from NgPost::parseCommandLine

Regards

**Comment by mbruel** [comment]
you're right...
I'll try to make a new release this weekend.

**Comment by mbruel** [comment]
the v1.5 is available.
when using the -f option, you must provide an email like string as Usenet is checking there is a @ followed by a dot.
I've also corrected the -z option ;) (no need of a email there, short small text is cool)

**Comment by AssRap3r** [comment]
this appears to be an issue in 4.2 again. uploader isn't respected when it's set in .ngPost or via command line
