### ISSUE TITLE
[QUESTION] Not able to download any AppImages

### ISSUE THREAD

**Issue by GreenLord** [mbruel/ngPost#40]
Not an technical problem, but im not able to download the AppImage, you're offering in the description here: https://github.com/mbruel/ngPost

/cheers :)

**Comment by mbruel** [comment]
They are available now ;)
When I release the code of a new Release it will trigger a Popup for your ngPost but I still need to build them on different stations...
So let me 15min and then they arrive.
The AppImage are available now.
Missing the RPI release and MacOS one (as someone is building it for me)
