### ISSUE TITLE
[Feature Request] Increased obfuscation options

### ISSUE THREAD

**Issue by AssRap3r** [mbruel/ngPost#41]
Feature request: Increase amount of obfuscation options

The current options are a good start but there can be some improvements to reduce the possibility of scraping and identifying. when used individually they'd only provide a limited benefit, but using them all together makes it incredibly complicated to scrape. 

1. Distribute files over multiple groups
2. Remove part numbers from subject line
3. Generate random subject file id
4. Generate random email for each file post

Issue with current method: 

- ngPost adds part numbers into the subject
- ngPost keeps the same random email for an entire post 
- ngPost doesn't randomize the names in the subject
- ngPost dumps posts into the same group

filenames, part numbers + unique email make it easy to scrape an entire post. You can see an example on xylo: https://www.binsearch.info/browse.php?bg=alt.binaries.xylo

(this has actually turned out longer than I expected, but I will keep it here since it's already done)

Example of 1 - post is distributed over multiple groups:
[01/03] "Test.part1.rar" alt.binaries.xylo MyName@ngPost.com
[02/02] "Test.part2.rar" alt.binaries.kenpsx MyName@ngPost.com
[03/03] "Test.part3.rar" alt.binaries.ftn MyName@ngPost.com

Example of 2 - part numbers removed:
"Test.part1.rar" alt.binaries.xylo MyName@ngPost.com
"Test.part2.rar" alt.binaries.xylo MyName@ngPost.com
"Test.part3.rar" alt.binaries.xylo MyName@ngPost.com

Example of 3 - subject id is randomized:
[01/03] "mSZXvxasKvPu16DMzwSCndwNILtsZDLK" alt.binaries.xylo MyName@ngPost.com
[02/03] "j5Iv6zo6yuRXicqWcrDA8U0kNc0FRPR5" alt.binaries.xylo MyName@ngPost.com
[03/03] "T7HzM1W8Im5BL6654BDdXLrzPln8WnM4" alt.binaries.xylo MyName@ngPost.com

Example of 4 - poster id is randomized
[01/03] "Test.part1.rar" alt.binaries.xylo jsdnaskjnd329@ngPost.com
[02/02] "Test.part2.rar" alt.binaries.kenpsx sakjhnskjhdiu2@ngPost.com
[03/03] "Test.part3.rar" alt.binaries.ftn askak298js@ngPost.com

--- as you can see, when used alone they don't provide much protection. you could still scrape via filename, part numbers, posters & group. when used together though:

Example of 1 + 2 - distributed over multiple groups with no part numbers
"Test.part1.rar" alt.binaries.xylo MyName@ngPost.com
"Test.part2.rar" alt.binaries.kenpsx MyName@ngPost.com
"Test.part3.rar" alt.binaries.ftn MyName@ngPost.com
 - could still be scraped by filename, although you'd have to search multiple groups. the uniqueness of the filename would make this a lot easier

Example of 1 + 2 + 3 - distributed over multiple groups, no part numbers, randomized subject id
"mSZXvxasKvPu16DMzwSCndwNILtsZDLK" alt.binaries.xylo MyName@ngPost.com
"j5Iv6zo6yuRXicqWcrDA8U0kNc0FRPR5" alt.binaries.kenpsx MyName@ngPost.com
"T7HzM1W8Im5BL6654BDdXLrzPln8WnM4" alt.binaries.ftn MyName@ngPost.com
 
Example of 1 + 2 + 3 + 4:  distributed over multiple groups, no part numbers, randomized subject id, randomized poster
"mSZXvxasKvPu16DMzwSCndwNILtsZDLK" alt.binaries.xylo jsdnaskjnd329@ngPost.com
"j5Iv6zo6yuRXicqWcrDA8U0kNc0FRPR5" alt.binaries.kenpsx sakjhnskjhdiu2@ngPost.com
"T7HzM1W8Im5BL6654BDdXLrzPln8WnM4" alt.binaries.ftn askak298js@ngPost.com

Just to say that personally I would have no use for 3 & 4 as I do compression & pars separately and then obfuscate the filenames. they could be useful for anyone that does everything via ngPost though. I'd be most interested in 1 & 2.

**Comment by mbruel** [comment]
Hi,

Well that is the goal to have your posts easy to find on public indexers. But with an obfuscated name and password. So only you and your community would know what it is and be able to unpack it. You can then keep your post in database, no need to keep the nzb files ;)
That is why I'm filling the ngPost_history.csv.

What is your goal in obfuscation? option 3 and 4 acts on each Files. ngPost is doing even further  and doing the same on Articles if you really want. Meaning you can't even reconstruct a File...

I can understand option 1 and 2 but they break finding your post on public indexers that is why I didn't add them. what is the benefit?

if you really want those features, I can add them for you against a little contribution. Let me know if you're interested.

**Comment by AssRap3r** [comment]
>Well that is the goal to have your posts easy to find on public indexers. But with an obfuscated name and password. So only you and your community would know what it is and be able to unpack it. You can then keep your post in database, no need to keep the nzb files ;)

personally if i'm obfuscating it's because i **don't** want public indexers to be able to easily identify what i'm posting. it seems like a workaround for an issue that's already solved by nzbs. i wouldn't want to rely on public indexers to find my lost post - what if they don't index the group, has lots of parts missing, or falls outside of their group retention limit? i'd say that most nzbs can easily be redownloaded from the indexer you post them to. 

> What is your goal in obfuscation?
> what is the benefit?

the goal/benefit is to achieve a way of posting that's secure enough **without** having to resort to passwording archives. i'm trying to utilize the middle ground between plain text publicly indexable posts (usable by everyone) and randomly named passworded archives (usable by only those with the password). currently, you could piece together x parts from my posts and get a usable file. i just want to make it a little more difficult to achieve that.

**Comment by mbruel** [comment]
> i wouldn't want to rely on public indexers to find my lost post - what if they don't index the group, has lots of parts missing, or falls outside of their group retention limit?

well public indexers or browsing Usenet via your grabber... same same ;)

> i'd say that most nzbs can easily be redownloaded from the indexer you post them to.

what if your indexer closes?... or you loose your access?

> the goal/benefit is to achieve a way of posting that's secure enough without having to resort to passwording archives.

you can do article obfuscation if you don't want to use a password... (but then the file name obfuscation you do outside ngPost is useless)

This would take me some time and I don't really see who would use this middle ground...
if you send me like 20€, I'll code it for you.

**Comment by AssRap3r** [comment]
>what if your indexer closes?... or you loose your access?

i like to assume that the uploader is keeping their nzbs somewhere safe. after all, what happens to ngPost_history.csv if your hdd crashes :P 

>you can do article obfuscation if you don't want to use a password... (but then the file name obfuscation you do outside ngPost is useless)

i tried article obfuscation (with a normal rar set) and saw no difference in the result - the filename was no different in either the nzb or public indexer...maybe i'm missing something. it sounds like -x should do what suggestion 3 is asking?  if that were the case i wouldn't need the other changes, because a randomized article subject would eliminate the grouping issue. 

"Do article obfuscation (the subject of each Article will be a UUID)"
obfuscated nzb:   
```<file poster="puNuQonKZKDR5@ngPost.com" date="1587325010" subject="[1/3] - &quot;1GB.part01.rar&quot; yEnc (1/74) 52480000">```
unobfuscated nzb:   
```<file poster="Test &lt;test@icl.es&gt;" date="1587323786" subject="[1/3] - &quot;1GB.part01.rar&quot; yEnc (1/74) 52480000">```

I enabled GEN_FROM in case that was required, but it didn't change the outcome.

**Comment by mbruel** [comment]
if you use article obfuscation, you won't be able to find your post on public indexer.
the "file subject" doesn't need to be obfuscated as it is only there in the nzb. It allows to reconstruct properly.

**Comment by DEVUVO** [comment]
hmmm sounds like i agree with it but as ngpost man said , this will take some time , maybe you can donate some because it think this will take more codes and more time ,
i like the idea of the 4 points , however the first 2 options are very useful but if you look deeper you will for sure request the 2 other options 3 + 4 to make it ever , 

this make me think of an option to make a full random email with random @***.*** instead of all posts will be @ngpost.com 

great idea i vote up for it.

**Comment by AssRap3r** [comment]
> if you use article obfuscation, you won't be able to find your post on public indexer.
> the "file subject" doesn't need to be obfuscated as it is only there in the nzb. It allows to reconstruct properly.

alright, gave this a try yesterday night and have allowed it about 10 hours to propagate. looks like you're right - articles aren't appearing (so far) on public indexers (except for par2 collection). i can live with that for now

on another note - did something change with how the from email is exported? i'm seeing "User &lt;user@domain.ltd&gt;" instead of "User <user@domain.ltd>": https://www.binsearch.info/?max=250&g=alt.binaries.test&a=Test+%26lt%3Btest%40icl.es%26gt%3B

not a big deal since newznab displays it properly, but showing the &lt; makes me think i'm doing something wrong

**Comment by mbruel** [comment]
>  articles aren't appearing (so far) on public indexers (except for par2 collection). i can live with that for now

No par2 can't be visible neither. you're not looking at the good post.

> Im seeing "User <user@domain.ltd>" instead of "User user@domain.ltd"

Well I suppose the right way would be "User <user@domain.ltd>" like in emails...
But I'm not using it. You should put only an email, no space. 
I don't think this format  "User user@domain.ltd" is used.

Again, I think you're not looking at the good post... (especially if you used Article obfuscation, as I said, I'm certain 100% you CAN'T find anything nowhere. Only using the NZB file)

**Comment by AssRap3r** [comment]
> No par2 can't be visible neither. you're not looking at the good post.

whoops, looks like you're right. the last indexed was from the previous batch which was also done yesterday. i think we can put this change on hold then since there's no immediate benefit to my proposal. 

appreciate the time you spent helping :)

**Comment by kadfnu** [comment]
I realy like the idea to see options 1+2+3+4 together, pls implement this. would it be possible ???

it can be called "paranoid obfuscation" then. :-)

A contribution would be okay (Amazon coupon code then?)

Regards

**Comment by mbruel** [comment]
I don't like amazon...
bitcoins or paypal if you want.
but if it is to get my work stolen by wtf, they can implement it themself or contact me directly!
