### ISSUE TITLE
Should use another connection to post if one fails

### ISSUE THREAD

**Issue by pankkake** [mbruel/ngPost#42]
For the context, I don't think it happened under 4.6, but it might also be because one of the providers I use to post had issues just recently.
Anyway, I use 3 separate providers to post. When one provider has issues, I get stuff like that in the end:

```
[=================================================>] 99 % (76429 / 76441) avg. speed:  13.01 MB/s[Poster #6 {NntpCon #14}] Error Socket: The TLS/SSL connection has been closed                                   
Error: disconnected connection: #14                                                       
                                                                                          
[Poster #6 {NntpCon #13}] Error Socket: The TLS/SSL connection has been closed            
Error: disconnected connection: #13                                                       
                                                                                          
[Poster #7 {NntpCon #16}] Error Socket: The TLS/SSL connection has been closed            
Error: disconnected connection: #16                                                       
                                                                                          
[Poster #7 {NntpCon #15}] Error Socket: The TLS/SSL connection has been closed            
Error: disconnected connection: #15                                                       
                                                                                          
we lost all the connections...                                                            
Sleep for 30 sec before trying to reconnect                                               
Pause posting...                                                                          
[=================================================>] 99 % (76429 / 76441) avg. speed:  12.91 MB/sTry to resume posting
Resume posting...                                                                         
[=================================================>] 99 % (76440 / 76441) avg. speed:  12.82 MB/s[Poster #5 {NntpCon #12}] Socket Timeout (30000 ms)                                                              
[Poster #5 {NntpCon #12}] Connection lost, trying to reconnect! (nb disconnected: 1)      
[==================================================] 100 % (76441 / 76441) avg. speed:  12.82 MB/s
                                                                                          
[11:19:24.374] Upload size: 50.99 GB in 01:07:52.955 (4072 sec)                  => average speed:  12.82 MB/s (16 connections on 16 threads)                                                                     
4 / 76441 articles FAILED to be uploaded (even with 10 retries)...                    
```    

```
[=================================================>] 99 % (76438 / 76441) avg. speed:  15.38 MB/s[Poster #2 {NntpCon #3}] Error Socket: The TLS/SSL connection has been closed
[Poster #2 {NntpCon #3}] Connection lost, trying to reconnect! (nb disconnected: 9)
[Poster #5 {NntpCon #6}] Error Socket: The TLS/SSL connection has been closed
[Poster #3 {NntpCon #4}] Error Socket: The TLS/SSL connection has been closed
[Poster #5 {NntpCon #6}] Connection lost, trying to reconnect! (nb disconnected: 9)
[Poster #3 {NntpCon #4}] Connection lost, trying to reconnect! (nb disconnected: 9)
[Poster #1 {NntpCon #2}] Error Socket: The TLS/SSL connection has been closed
[Poster #1 {NntpCon #2}] Connection lost, trying to reconnect! (nb disconnected: 9)
[Poster #4 {NntpCon #5}] Error Socket: The TLS/SSL connection has been closed
[Poster #4 {NntpCon #5}] Connection lost, trying to reconnect! (nb disconnected: 9)
[Poster #0 {NntpCon #1}] Error Socket: The TLS/SSL connection has been closed
[Poster #0 {NntpCon #1}] Connection lost, trying to reconnect! (nb disconnected: 9)
[=================================================>] 99 % (76438 / 76441) avg. speed:  15.37 MB/s[Poster #7 {NntpCon #8}] Error Socket: The TLS/SSL connection has been closed
[Poster #7 {NntpCon #8}] Connection lost, trying to reconnect! (nb disconnected: 9)
[=================================================>] 99 % (76438 / 76441) avg. speed:  14.13 MB/s[Poster #2 {NntpCon #3}] Error Socket: The TLS/SSL connection has been closed
[Poster #2 {NntpCon #3}] Connection lost, trying to reconnect! (nb disconnected: 10)
[Poster #3 {NntpCon #4}] Error Socket: The TLS/SSL connection has been closed
[Poster #3 {NntpCon #4}] Connection lost, trying to reconnect! (nb disconnected: 10)
[Poster #4 {NntpCon #5}] Error Socket: The TLS/SSL connection has been closed
[Poster #4 {NntpCon #5}] Connection lost, trying to reconnect! (nb disconnected: 10)
[Poster #5 {NntpCon #6}] Error Socket: The TLS/SSL connection has been closed
[Poster #5 {NntpCon #6}] Connection lost, trying to reconnect! (nb disconnected: 10)
[Poster #1 {NntpCon #2}] Error Socket: The TLS/SSL connection has been closed
[Poster #1 {NntpCon #2}] Connection lost, trying to reconnect! (nb disconnected: 10)
[Poster #0 {NntpCon #1}] Error Socket: The TLS/SSL connection has been closed
[Poster #0 {NntpCon #1}] Connection lost, trying to reconnect! (nb disconnected: 10)
[=================================================>] 99 % (76438 / 76441) avg. speed:  14.12 MB/s[Poster #7 {NntpCon #8}] Error Socket: The TLS/SSL connection has been closed
[Poster #7 {NntpCon #8}] Connection lost, trying to reconnect! (nb disconnected: 10)
[=================================================>] 99 % (76438 / 76441) avg. speed:  13.07 MB/s[Poster #4 {NntpCon #5}] Error Socket: The TLS/SSL connection has been closed
Error: disconnected connection: #5

[Poster #5 {NntpCon #6}] Error Socket: The TLS/SSL connection has been closed
Error: disconnected connection: #6

[Poster #0 {NntpCon #1}] Error Socket: The TLS/SSL connection has been closed
Error: disconnected connection: #1

[Poster #2 {NntpCon #3}] Error Socket: The TLS/SSL connection has been closed
Error: disconnected connection: #3

[Poster #1 {NntpCon #2}] Error Socket: The TLS/SSL connection has been closed
Error: disconnected connection: #2

[Poster #3 {NntpCon #4}] Error Socket: The TLS/SSL connection has been closed
Error: disconnected connection: #4


we lost all the connections...
Sleep for 30 sec before trying to reconnect
Pause posting...
[=================================================>] 99 % (76438 / 76441) avg. speed:  12.97 MB/sTry to resume posting
Resume posting...
[==================================================] 100 % (76441 / 76441) avg. speed:  12.96 MB/s

[15:26:16.665] Upload size: 50.99 GB in 01:07:07.503 (4027 sec)                  => average speed:  12.96 MB/s (8 connections on 16 threads)
1 / 76441 articles FAILED to be uploaded (even with 10 retries)...

```

The first try was with -x, and the nzb ended up having post IDs that were missing (I checked with nzbverify). Oddly, the second nzb without -x (and also less connections) had no missing post IDs (but maybe they were never written?).

Anyway, I think it would make sense to try with connections from another provider instead of retrying with the same.

**Comment by mbruel** [comment]
Hi,
hum... an Article is affected to ONE connection. This one has a number of retry. In normal circumstance, it should be fine, and you should manage to post it.
I don't know what's your provider... Do you have often those Error Socket?
It's not a big deal if you've 1 or 4 articles that failed... I supposed you're using par2.
The -x option has nothing to do with the number of articles that couldn't be posted.
Do you have this error message: "Socket Timeout ..." ?
Do you compile from the sources? what's your OS?

**Comment by pankkake** [comment]
> an Article is affected to ONE connection

I understand that, but I would like it to chose another on failure ;-)

> I don't know what's your provider... Do you have often those Error Socket?

It was ViperNews, and it's only recent.

> It's not a big deal if you've 1 or 4 articles that failed... I supposed you're using par2

On these posts, the failures were on the .par2 files so it was no big deal, but still, I would like to post all articles to avoid lengthy repairs.

One of the reasons I use ngPost is multi-server support, and since I use 3 providers, if ANY of the 3 has a failure I will have missing articles! So by using 3 providers... I multiply by 3 the chance of having missing articles. :-( If it did try on another connection, it would be the opposite, having more providers would bring more reliability.

Even for pure speed, if one provider has a temporary issue, using another one on failure should be better.

> Do you compile from the sources? what's your OS?

Yes, I'm on commit 8ce7aee9ad9fe1807464c9384d4c8a54243e54be and compiling under Debian 10.

**Comment by mbruel** [comment]
> I understand that, but I would like it to chose another on failure ;-)

ngPost is not designed to differentiate the Connections. It can just create some to any servers and mix them but once then the server itself doesn't matter.
Providers should have a good quality of service...

Can you see this trace: "FAIL posting %1 (Error: '%2')"
I suppose you don't and you're just getting disconnected...

I suppose you could try to increase the number of tries for bad providers... If with 10 retries you get only 4 failure on 76441, that's nothing. 4*700k = 2.73 MB on a post of 50.99 GB!
So try with 20 retries... and it should be fine....

> On these posts, the failures were on the .par2 files so it was no big deal, but still, I would like to post all articles to avoid lengthy repairs.

Repair would be quite fast if you're just missing few articles.


> One of the reasons I use ngPost is multi-server support, and since I use 3 providers, if ANY of the 3 has a failure I will have missing articles! So by using 3 providers... I multiply by 3 the chance of having missing articles. :-( If it did try on another connection, it would be the opposite, having more providers would bring more reliability.

well I've allowed to use multiple-server because I could :) haha and essentially to get a better upload multiplying the number of connections. it was not in the goal of anticipating failure on the side of a provider...
It could be done, but it would take some time to analyse a way to implement it. I'm not sure it is worthing it.


> Even for pure speed, if one provider has a temporary issue, using another one on failure should be better.

I don't think this is true. Cause if a provider has issues, you're still using all the other connections for the rest of the Articles. Only few Articles affected to the connection of this provider are "on hold"  and could end up failed. But then those Connections would be closed for good and the continue only with the other providers.
In your example I suppose you only had 1 provider, the bad one, and you end up with all the Connection closed. This probably wouldn't be the case if you were using another provider aside this one.


So I'm not planning to implement this. If it was really need I would, but as you said, just skip using ViperNews would be the way to go ;) 
Or maybe write to them asking them why they have such issues...

Are you sure it's not on your side that you got a connection issue? Is it happening all the time and with Viper only?

**Comment by Pascal16230** [comment]
bonjour

j'ai aussi le meme souci , post incomplets avec vipernews , eweka et newshosting

j'utilise ngpost depuis très longtemps mais depuis quelques temps il ne fonctionne plus correctement
