### ISSUE TITLE
[Request] Queueing - and save to a queue file

### ISSUE THREAD

**Issue by Tr4il** [mbruel/ngPost#43]
Hi!

I was thinking about a handy feature wherein ngPost creates a queue file from the quick jobs I have setup but not started posting yet, saving that queue file and then use that to trigger the posting from the commandline rather than the HMI/GUI.

I have no idea if this is possible, but it seemed like a good idea to me.

Edit: If you have ever used Handbrakes Queue feature and queue file feature, you'll know what I mean.

**Comment by mbruel** [comment]
Hi,
I've never used HandBrake but I kind of see what you mean.
I don't see the interest in using the GUI to prepare the job and then use the CMD... If you use the GUI why not posting with it?

I guess I could add the feature to save/load the QuickJobs but that's quite some work:
- to define the text file format
- do the serialization (save / load the files)
- check the jobs are still valid (you have move or deleted files included in the Job)

So for ngPost, I don't think this is useful. When you want to post something, you don't delay it in general. It's not resource consuming like compressing a movie.

Plus in the latest version, I've added the pause feature. So if you want to get the full bandwidth, you can Pause and resume when you're done.

And finally you've the --auto and --monitor features. It is simple to use those and use a specific folder for yours posts...

So I won't implement this feature. It could be reopened later if other people find interest to it but I doubt it.

**Comment by Tr4il** [comment]
> I don't see the interest in using the GUI to prepare the job and then use the CMD... If you use the GUI why not posting with it?

Because I use your fantastic piece of software on my remote server :)
That way I could prepare the post(s) via VNC using the GUI and then use tmux or screen to actually start the post while I am not even connected to the server. 

> It's not resource consuming like compressing a movie.

The compression/rar splitting is though.

I know it all sounds a bit ... dumb. It's just what works for me.
Thanks for responding though, I appreciate it.

**Comment by mbruel** [comment]
I don't know tmux, I'll check that.
You should use x2go instead of vnc. Much safer, faster and it's the equivalent of screen with graphical layer.
Otherwise use X forwarding I guess there could be a trick to attach / detach the GUI.
But easy way would be to use x2go ;)

**Comment by Tr4il** [comment]
x2go always seemed a bit slower than VNC, but I'll check it out again, thanks!

**Comment by mbruel** [comment]
I've checked and it seems it's not possible to attach/detach a GUI using X forwarding...

I'm going to play a little bit around that and check if I can do it in ngPost using signals to switch from CMD to GUI mode. Could be cool :)
I'll at least allow the possibility to switch from the GUI to CMD so you can launch it from screen with the GUI, prepare all your Posts and then run in CMD ;)
We'll see about the reattach, maybe using SIGUSR1

**Comment by mbruel** [comment]
well not sure we can survive a disconnection once we've created some GUI element :|
I'm waiting for [some answers from the QT community](https://forum.qt.io/topic/114855/avoid-crashing-qapplication-when-closing-the-x11-connection-typically-screen-a-gui-app-after-destroying-its-qmainwindow).

**Comment by DEVUVO** [comment]
I think creating pre post jobs and save it for a later time to post would be the idea even so the idea on this thread is just one guy maybe , will it benefit many people for the remote thing maybe in the future but right now we need to focus on top important features. thanks for the idea as well
