### ISSUE TITLE
Feature Request: Maximum upload speed

### ISSUE THREAD

**Issue by sirjaymz** [mbruel/ngPost#46]
Feature Request:
To limit the maximum upload speed of ngPost to a specified value. If it's not achieved, it does not throttle, however, if the max upload speed is achievable, allow user to specify maximum upload speed.

Suggestion:

--max_speed                       : limit max data throughput of all combined connections/threads.
Set's maximum upload speed of all connections combined to X speed per second specified in KiB, (kilo-bytes per second), 
e.g. 3500 or 10000
e.g. (--max_speed 3500)

**Comment by mbruel** [comment]
This won't be done in ngPost.
It was requested before, cf [Req #17 ](https://github.com/mbruel/ngPost/issues/17).
Use an external software to do that if you need.
For windows have a look [here](https://www.howtogeek.com/347711/how-to-limit-any-applications-bandwidth-on-windows/), for Linux check trickle or lower level tc (traffic control).

**Comment by BakasuraRCE** [comment]
Just to complementing is you animate to do, it can be done with Token Bucket Algorithm
https://en.wikipedia.org/wiki/Token_bucket
https://github.com/wolkykim/qlibc

**Comment by mbruel** [comment]
interesting this Token Bucket algorithm but it doesn't change the thing that the whole architecture needs to get heavier with a socket scheduler and some timers...
the goal of ngPost was to be as fast as possible relying on fully asynchronous sockets.
if you want to decrease the uploading rate, you can just play on the number of connections. In general it's quite reliable. Make some test with 1 connection to get the rate you can reach, with 2, with 3... and choose accordingly.
