### ISSUE TITLE
Adding support for UTF-8

### ISSUE THREAD

**Issue by neant1122** [mbruel/ngPost#47]
Dear ngpost developer,

First of all, I want to thank you for creating this wonderful tool for us! It's very easy to use!

Can I request you make ngpost to support UTF-8? When I upload something with Chinese/Japanese characters as the folder name, the NZB that ngpost created only show the Latin characters. Is that possible the name of the NZB file is exactly the same as the folder/file's name, even the name contains Asian characters?

Thanks for your time, and stay safe and healthy!

![2020-06-06_170144](https://user-images.githubusercontent.com/14261753/83956242-ff0dd700-a818-11ea-921c-f6cae0282681.png)

**Comment by mbruel** [comment]
Hi,
Are you using the latest version of ngPost (v4.7)?
Check the configuration file (ngPost.conf on Windows or ~/.ngPost  on Linux/Mac)
You should set `NZB_RM_ACCENTS` to false.
```
## remove accents and special characters from the nzb file names
NZB_RM_ACCENTS = true
```
This might be enough.
Please confirm.

PS: would you be interested in translating the app in Chinese or Japanese?

**Comment by neant1122** [comment]
Hi mbruel,
Thank you so much for your reply! It works for me!
Do you have any instructions that I can follow for translating the app in Chinese? 

Thanks for your time!

**Comment by mbruel** [comment]
That would be great if you could take a bit of time to have a Chinese version! :)
it's quite easy, Qt provides a tool to do it with a nice GUI.
Are you on Windows?
Drop me an email and I'll send you the instructions like I did for the other languages.
my email is: Matthieu.Bruel@gmail.com
Cheers!

PS: I close the issue then ;)
