### ISSUE TITLE
Feature Request: Compress nzb files

### ISSUE THREAD

**Issue by BakasuraRCE** [mbruel/ngPost#49]
Feature Request:
Compress nzb files to save space, I tested a single nzb file of 100 kb and the result was 20kb because the format of nzb that is text, this can save time and BIG space for archiving tasks.

Thanks.

**Comment by mbruel** [comment]
Hi
I'm not aware of indexers or grabbers that can use compressed nzb.
Is there?
What kind of compression? Gzip or Bzip2 so it can be done on the fly?

**Comment by BakasuraRCE** [comment]
Yes, the system can extract the metadata for index and to get the nzb back just use Gzip or Bzip2, they are soft to CPU.

I thing this more like an check option if you need it.

**Comment by mbruel** [comment]
there is no real benefit for a poster to compress on the fly.
I could zip or gzip but that means depending on an external lib (lzip).
maybe the easiest way would be with a call to an external command.
I was thinking to add the possibility to run an external script (or command) once the nzb is produced.
I guess that would be the way to go. In parameter you would have the full path of the nzb so you could zip it or tar.bz2 it and then curl it to publish it on an indexer or scp it...
what you think?

**Comment by BakasuraRCE** [comment]
Is a good idea, more generic, can be a list of hooks(like the list of servers) to be called synchronously(or not) at end of generation of nzb

**Comment by mbruel** [comment]
well one should be fine.
If you want several, just use a shell script (or batch file on Windows..)
This is [on my backlog since a while](https://github.com/mbruel/ngPost/blob/7528c7274b8ab4b2ce7df5c5c07ac26c870779a7/src/NgPost.cpp#L72), let's see I may add it for the v4.8 with the Chinese translation :)

**Comment by mbruel** [comment]
[NZB_POST_CMD](https://github.com/mbruel/ngPost/blob/680e69d32d17f3c226bb36303b83041702a129a7/ngPost.conf#L26) is implemeted and pushed.
it will be included in the v4.8 which should arrive by the end of the week.
just use the second example: `NZB_POST_CMD = zip %1.zip %1`
