### ISSUE TITLE
 [Bug] limit rar number is not saved to config file

### ISSUE THREAD

**Issue by BakasuraRCE** [mbruel/ngPost#51]
The GUI option 'limit rar number' is not being saved to .ngPost file

**Comment by mbruel** [comment]
Well this is a conf only feature as you're not supposed to change it. I'm going to disable the checkbox so you can't change it from the GUI and I'll update the tooltip.
Basically the Checkbox is ticked only if RAR_MAX is defined in the conf
```
## maximum number of archive volumes
## we'll use RAR_SIZE except if it genereates too many volumes
## in that case we'll update rar_size to be <size of post> / rar_max
RAR_MAX = 99
```
