### ISSUE TITLE
Unit and functional tests

### ISSUE THREAD

**Issue by BakasuraRCE** [mbruel/ngPost#53]
Maybe start to think about tests is a good idea?

Some like https://github.com/sabnzbd/sabnzbd/issues/999

**Comment by mbruel** [comment]
Hi,
well... I don't really feel the need to have unit tests.
I've done manual checks from the beginning.
When I add new features, I'm careful to not do any regression.

**Comment by BakasuraRCE** [comment]
Well, that could be good now but when the project grows more and the first waves of pull request arrive in combination to support 3 operating systems and the complexity growing due to the new functionalities and possible very specific configurations to support some buggy system it would really be a pain upside down.

Of course implementing this is a great job and takes time, we could start with an automatic release generation process using [GitHub](https://help.github.com/en/actions/getting-started-with-github-actions) [Actions](https://github.com/marketplace?type=actions&query=release) to ensure that things like [this](https://github.com/mbruel/ngPost/issues/52) are not a waste of time.

**Comment by mbruel** [comment]
As you said it's time consuming and I won't loose time to do it for several reasons:

- I believe the app is quite complete nowadays... There shouldn't be so many new features arriving and if so they should not impact the existing functionalities.

- I've never done GUI unit testing. I guess there are possibilities but it's quite heavy. I'd rather rely on users to identify bugs and correct them on future versions. 

- As the project is made in Qt, there shouldn't be issues for a specific architecture. It should behave the same on all OS.

But if people wants to create unit tests, I'm happy to help doing it. The ideal configuration would be to use [Qt Test framework](https://doc.qt.io/qt-5/qtest-overview.html) with a different pro file.

**Comment by BakasuraRCE** [comment]
Respectable, could you tell me the steps to build an AppImage for Linux?

I would like to start working on the release system by commit.

**Comment by mbruel** [comment]
It's specific to Qt, I'm using [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) that does all the job for you.
For Mac, it's not me who's doing it, but you've the equivalent: macdeployqt.

For Linux, you shouldn't use a environment too recent, it won't work. I'm building on a Debian 9.11 with GLIBC 2.24-11. (Failing on my Laptop with a Debian 10.4 and GLIBC 2.28-10)

Other than that, it's just a one command line
`~/apps/linuxdeployqt-6-x86_64.AppImage ngPost_v4.7/ngPost.desktop -appimage -qmake=/opt/Qt/5.12.6/gcc_64/bin/qmake`

The desktop image is standard:
```
[Desktop Entry]
Type=Application
Name=ngPost
Exec=ngPost %F
Icon=ngPost
Comment=Edit this default file
Terminal=true
Categories=Network;
X-AppImage-Version=
```

What do you mean a release system by commit? continuous integration? Jenkins?

Personally I don't use the Appimage for testing. It's useless and a loss of time. It's enough to compile, make sure there are no errors, then launch the app (or the test app) after having set up correctly your LD_LIBRARY_PATH...
