### ISSUE TITLE
[Feature Request] Pause the posting if the disk is full

### ISSUE THREAD

**Issue by awsms** [mbruel/ngPost#55]
I realized I had a ton of defective nzbs, because when the disk is full, ngPost keeps posting and writting the .nzb on nothing....
I wish there was a prompt, like RAR and ParPar uses, `Your disk is full, [R]esume [Q]uit` in the CLI. Haven't tried the GUI yet but I guess it would be something similar?

**Comment by mbruel** [comment]
well what you mean?
I've never experienced disk full, it's not something you should do ;) haha
but I'd expect both rar or par2 to exit with an error no? (exit code different from 0)
if rar or par2 fail, normally ngPost doesn't proceed...

**Comment by awsms** [comment]
> well what you mean?

It happened me a few times (yeah I'm the unluckiest guy in the world) that my disk went full just during the posting process (around 50-55%), so the post is messed up and I only realized waayyy after, when I try to download again what I posted. :(

**Comment by mbruel** [comment]
how can the disk get full during posting?
it should still work as it is just reading files.
the only thing that could fail is writing in the nzb file but I don't think I've made any robustness around that...

**Comment by mbruel** [comment]
anyway...
this situation should not happen, I'm not going to introduce a check on that.
