### ISSUE TITLE
CI releases

### ISSUE THREAD

**Issue by BakasuraRCE** [mbruel/ngPost#58]
Hi,

I was trying to create the CI system [here](https://github.com/BakasuraRCE/ngPost/blob/master/.github/workflows/main.yml) but I'm getting the error "[Could not determine the path to the executable based on the desktop file](https://github.com/BakasuraRCE/ngPost/runs/820961470?check_suite_focus=true#step:4:313)"

Can you help me know what I did wrong in creating the AppImage?

Thanks.

**Comment by mbruel** [comment]
well you need to compile ngPost and put the executable in the same folder of the desktop file.

**Comment by BakasuraRCE** [comment]
Haha nice, please check here: https://github.com/mbruel/ngPost/pull/59
