### ISSUE TITLE
Error Socket: TLS initialization failed

### ISSUE THREAD

**Issue by noobcoder1983** [mbruel/ngPost#60]
Hi,

got some strange errors with the new 4.9 version. I tried two usenet servers for upload testing but always got these errors.

I can ping the usenet server, so it should be online.

```
[Poster #0 {NntpCon #4}] Error Socket: TLS initialization failed
Error: disconnected connection: #4

[Poster #2 {NntpCon #9}] Error Socket: TLS initialization failed
[Poster #2 {NntpCon #9}] Connection lost, trying to reconnect! (nb disconnected: 29)
[Poster #9 {NntpCon #32}] Error Socket: TLS initialization failed
Error: disconnected connection: #32

[Poster #6 {NntpCon #22}] Error Socket: TLS initialization failed
Error: disconnected connection: #22

[Poster #5 {NntpCon #19}] Error Socket: TLS initialization failed
Error: disconnected connection: #19

[Poster #7 {NntpCon #24}] Error Socket: TLS initialization failed
Error: disconnected connection: #24

[Poster #2 {NntpCon #9}] Error Socket: TLS initialization failed
[Poster #2 {NntpCon #9}] Connection lost, trying to reconnect! (nb disconnected: 30)
[Poster #2 {NntpCon #9}] Error Socket: TLS initialization failed
Error: disconnected connection: #9

we lost all the connections...
Sleep for 30 sec before trying to reconnect
Pause posting...
[>                    
```

Have I done something wrong?

Regards

**Comment by mbruel** [comment]
hum... what OS? 
I'm assuming you're on Windows, is that right? what version (32bt or 64bit?)
Sounds like there is an issue with the openssl dlls...
Please activate the Debug mode, with level 2. Use ony 1 connection to the server, no need to have 30 to fail. You should see a log message like this: `SSL support: no, build version: 1.1.1d, system version: 1.1.1c`
please give me the message.
if you're command line, use --full-debug to get the message.
Are you on Windows?

**Comment by mbruel** [comment]
@noobcoder1983 any updates on this? do you still have the issue or shall I close the thread?

**Comment by noobcoder1983** [comment]
@mbruel sorry forgotten to close it.

Think was a seedhost provider issue and not the fault of ngpost.

**Comment by noobcoder1983** [comment]
@mbruel sorry I tried it again with --fulldebug. Also tried with different usenet accounts - same error.

Seedhost provider told me they do not block uploads. Ubuntu 16.04.11 is running on their server.

Before it worked without problems, here a part of the output:

`[Poster #8 {NntpCon #27}] Error Socket: TLS initialization failed
[Poster #8 {NntpCon #27}] Connection lost, trying to reconnect! (nb disconnected: 28)
[Poster #17 {NntpCon #45}] Error Socket: TLS initialization failed
[Poster #17 {NntpCon #45}] Connection lost, trying to reconnect! (nb disconnected: 27)
[Poster #12 {NntpCon #35}] Error Socket: TLS initialization failed
[Poster #12 {NntpCon #35}] Connection lost, trying to reconnect! (nb disconnected: 29)
[Poster #8 {NntpCon #27}] SSL support: no, build version: OpenSSL 1.1.1d  10 Sep 2019, system version: 
[Poster #17 {NntpCon #45}] SSL support: no, build version: OpenSSL 1.1.1d  10 Sep 2019, system version: 
[Poster #12 {NntpCon #35}] SSL support: no, build version: OpenSSL 1.1.1d  10 Sep 2019, system version: `

and so on.

I am using **ngPost_v4.9-x86_64.AppImag**e with **parpar** on the server.

Thanks for help.

**Comment by mbruel** [comment]
I suppose [ngPost v4.8 ](https://github.com/mbruel/ngPost/releases/download/v4.8/ngPost_v4.8-x86_64.AppImage) is not either on your box is it? please confirm.

I guess you just need to install libssl1.1. In general it's coming with openssl.
if you have it, please tell me the version.
```
# apt-cache show libssl1.1:amd64
Package: libssl1.1
Source: openssl
Version: 1.1.1d-0+deb10u3
Installed-Size: 4077
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Architecture: amd64

# apt-cache show openssl
Package: openssl
Version: 1.1.1d-0+deb10u3
```
Otherwise, install openssl.

How old is Ubuntu 16.04.11?
Can you try  [this version compiled on a Debian 8 env](https://github.com/mbruel/ngPost/releases/download/v4.9/ngPost_v4.9-x86_64_debian8.AppImage)?

**Comment by noobcoder1983** [comment]
No on this box I use only version 4.9.

Attached you find the versions of openssl:

`Package: libssl1.1
Status: install ok installed
Priority: important
Section: libs
Installed-Size: 3416
Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Architecture: amd64
Multi-Arch: same
Source: openssl
Version: 1.1.0f-2~ubuntu14.04.1+deb.sury.org+1
Depends: libc6 (>= 2.14), debconf (>= 0.5) | debconf-2.0
Pre-Depends: multiarch-support
Breaks: salt-common (<= 2016.3.3+ds-3)
Description: Secure Sockets Layer toolkit - shared libraries
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It provides the libssl and libcrypto shared libraries.
Description-md5: 88547c6206c7fbc4fcc7d09ce100d210
Homepage: https://www.openssl.org/










Package: openssl
Architecture: amd64
Version: 1.0.2g-1ubuntu4.16
Priority: standard
Section: utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 934
Depends: libc6 (>= 2.15), libssl1.0.0 (>= 1.0.2g)
Suggests: ca-certificates
Filename: pool/main/o/openssl/openssl_1.0.2g-1ubuntu4.16_amd64.deb
Size: 491968
MD5sum: e8adf4c397497244275f59f625c26ab9
SHA1: d8d90bcb331e9513404a33aef647adc92dfc950f
SHA256: 6e120fda0d35b65d85f746f20aa56bd10ba85380dc2be1e364400e6e3ec2a7c4
Description-en: Secure Sockets Layer toolkit - cryptographic utility
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It contains the general-purpose command line binary /usr/bin/openssl,
 useful for cryptographic operations such as:
  * creating RSA, DH, and DSA key parameters;
  * creating X.509 certificates, CSRs, and CRLs;
  * calculating message digests;
  * encrypting and decrypting with ciphers;
  * testing SSL/TLS clients and servers;
  * handling S/MIME signed or encrypted mail.
Description-md5: 9b6de2bb6e1d9016aeb0f00bcf6617bd
Task: standard, ubuntu-core, ubuntu-core, mythbuntu-frontend, mythbuntu-backend-slave, mythbuntu-backend-master, ubuntu-touch-core, ubuntu-touch, ubuntu-sdk-libs-tools, ubuntu-sdk
Supported: 5y

Package: openssl
Status: install ok installed
Priority: optional
Section: utils
Installed-Size: 934
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 1.0.2g-1ubuntu4.15
Depends: libc6 (>= 2.15), libssl1.0.0 (>= 1.0.2g)
Suggests: ca-certificates
Conffiles:
 /etc/ssl/openssl.cnf 7df26c55291b33344dc15e3935dabaf3
Description-en: Secure Sockets Layer toolkit - cryptographic utility
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It contains the general-purpose command line binary /usr/bin/openssl,
 useful for cryptographic operations such as:
  * creating RSA, DH, and DSA key parameters;
  * creating X.509 certificates, CSRs, and CRLs;
  * calculating message digests;
  * encrypting and decrypting with ciphers;
  * testing SSL/TLS clients and servers;
  * handling S/MIME signed or encrypted mail.
Description-md5: 9b6de2bb6e1d9016aeb0f00bcf6617bd
Original-Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>

Package: openssl
Priority: standard
Section: utils
Installed-Size: 934
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Architecture: amd64
Version: 1.0.2g-1ubuntu4
Depends: libc6 (>= 2.15), libssl1.0.0 (>= 1.0.2g)
Suggests: ca-certificates
Filename: pool/main/o/openssl/openssl_1.0.2g-1ubuntu4_amd64.deb
Size: 492190
MD5sum: 8280148dc2991da94be5810ad4d91552
SHA1: b5326f27aae83c303ff934121dede47d9fce7c76
SHA256: e897ffc8d84b0d436baca5dbd684a85146ffa78d3f2d15093779d3f5a8189690
Description-en: Secure Sockets Layer toolkit - cryptographic utility
 This package is part of the OpenSSL project's implementation of the SSL
 and TLS cryptographic protocols for secure communication over the
 Internet.
 .
 It contains the general-purpose command line binary /usr/bin/openssl,
 useful for cryptographic operations such as:
  * creating RSA, DH, and DSA key parameters;
  * creating X.509 certificates, CSRs, and CRLs;
  * calculating message digests;
  * encrypting and decrypting with ciphers;
  * testing SSL/TLS clients and servers;
  * handling S/MIME signed or encrypted mail.
Description-md5: 9b6de2bb6e1d9016aeb0f00bcf6617bd
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 5y
Task: standard, ubuntu-core, ubuntu-core, mythbuntu-frontend, mythbuntu-backend-slave, mythbuntu-backend-master, ubuntu-touch-core, ubuntu-touch, ubuntu-sdk-libs-tools, ubuntu-sdk`

Sorry I cannot try this Debian 8 env on a Debian 8 distro. I could try it on the seedbox if it helps?

**Comment by noobcoder1983** [comment]
So I tested the Debian 8 AppImage. It works without problems, maybe because of glibc 2.23 which is installed on Ubuntu 16?

Is that the reason or another issue in the compiled binary?

**Comment by mbruel** [comment]
hum I'm not sure... I would have think that if your libc is too old, the "normal" version (ngPost_v4.9-x86_64.AppImage) should not even launch but crash with an error at the start.
I'd have imagined your env is not using the right ssl lib. Indeed, it seems you've openssl 1.0.2 instead which is the old version.
I've also openssl 1.1.1 on my box (Debian8) where I build the "old" version. So I don't really understand...
Good thing it is working so ;)

When is the last time you upgraded your system?
```
apt-get update
apt-get upgrade
``` 
After those 2 commands you may have the latest openssl no?

If it was a link issue like I though, I guess your only option would have been to compile ngPost on your host. It's not complicated.

**Comment by noobcoder1983** [comment]
Oh ok strange.

I would update the system but it is not my system. I am using a shared seedbox.

I can run linuxbrew so I can compile in my $HOME directory.

How I should compile it in case it does not work anymore on the host?

**Comment by mbruel** [comment]
if the deb8 version is working, it will always work.
I don't know linuxbrew...
To build, it's easy, [cf here](https://github.com/mbruel/ngPost#how-to-build)
you need to have on your system at least build-essential (C++ compiler, libstdc++, make,...) and libssl-dev.
for qt, either you get qt5-default qt5-qmake from your repository or you install yourself by downloading it (no need to be root)

On my Debian8, I'm running an old Qt version: Qt5.8.0

Can you please try the normal [ngPost v4.8](https://github.com/mbruel/ngPost/releases/download/v4.8/ngPost_v4.8-x86_64.AppImage) and let me know if it works.
It is built with Qt v5.12.6
I've upgraded to Qt v5.15.0 only for the v4.9
But I suppose your box is an old env, so only the versions compiled for Debian8 should work

**Comment by mbruel** [comment]
@noobcoder1983 any update? could you try the v4.8 plz.
then probably close the issue also ;)

**Comment by noobcoder1983** [comment]
@mbruel tested ngPost v4.8 it works.

Thanks a lot for help!

**Comment by mbruel** [comment]
@noobcoder1983 hum if the v4.8 is working, it means that the issue on you box comes with Qt v5.15.0 dependencies. Maybe the glibc version as you said.
Well for the future versions, use the _debian8 release ;)

**Comment by noobcoder1983** [comment]
@mbruel ok great thanks good to know, hope this will work in future with the _debian8 release.

I hope that the server will be upgraded etc. that I can use the "normal" version. But it is ok now I know which version I have to use in the meantime.

**Comment by mbruel** [comment]
I won't update my debian8 env (it will stay with Qt v5.8.0) so all the new versions should work don't worry.
when a box is set up and work properly with an uptime of several years you don't migrate it to the latest kernel, only the security updates (but in general it is stable and safe already.)
