### ISSUE TITLE
Feature request: Allow several servers as command line parameters

### ISSUE THREAD

**Issue by Tensai75** [mbruel/ngPost#61]
Hi Matthieu

as discussed, it would be nice having the server parameters passed as one string (e.g. -S user:pass@news.provider.com:563:ssl) with the possibility to use the -S parameter repeatedly to use several servers in parallel when using ngPost on the command line.
This would make ngPost much more versatile when it is being used in upload scripts where the server information comes from a different source.

Have a nice vacation and thanks for your work!

Regards, Tensai

**Comment by mbruel** [comment]
done:
```
// you can provide servers in one string using -S and/or split the parameters for ONE SINGLE server (this will overwrite the configuration file)
	-S or --server     : NNTP server following the format (<user>:<pass>@)?<host>:<port>:<nbCons>:(no)?ssl
	-h or --host       : NNTP server hostname (or IP)
	-P or --port       : NNTP server port
	-s or --ssl        : use SSL
	-u or --user       : NNTP server username
	-p or --pass       : NNTP server password
	-n or --connection : number of NNTP connections
```

example: -S user:pass@news.provider.com:563:25:ssl or  -S news.provider.com:119:10:nossl

**Comment by mbruel** [comment]
@Tensai75 if you need, [here is a win64 build](https://files.fm/u/d8r4qz2s), just replace the exe.

**Comment by Tensai75** [comment]
Hi Matthieu

> -S user:pass@news.provider.com:563:25:ssl

This unfortunately does not work if the username is e.g. an email containg a "@" or also if the password contains an "@" or ":".

`Syntax error on server details for user@email.com:password@news.provider.com:563:20:ssl, the format should be: (<user>:<pass>@)?<host>:<port>:<nbCons>:(no)?ssl`

**Comment by mbruel** [comment]
@Tensai75 well indeed, I was quite too restrictive on the username. There is 2 options:
1.: the username can't have a `:` and the password can't have a `@`
2.: I change the 2 first separators for example by triple them: `user@ngpost.com:::myPassword@123!@@@news.provider.com:563:20:ssl`

I guess it's quite common to not have a `:` in the username. Probably for the password too as you'd have the same issue connecting by ssh or ftp...
Maybe a mix between the 2 with only a triple `@`  between the password and host?

**Comment by mbruel** [comment]
Should be fine now.
so no `:` in the username, whatever in the pass and then a triple `@` to separate password and host
