### ISSUE TITLE
Use of meaningful exit codes on fatal errors

### ISSUE THREAD

**Issue by Tensai75** [mbruel/ngPost#63]
I have just noticed that when using ngPost on the command line for a quick post, ngPost does exit with exit code 0 nevertheless whether the upload was successful, or the program terminated prematurely due to a fatal error.
E.g. if the input folder provided with parameter -i is not readable or does not exist, ngPost exits with exit code 0. However, in such cases, when a fatal error prevents ngPost from performing the upload, ngPost should exit with an error or at least with an exit code > 0.
This is especially important if ngPost is used with scripts depending on the exit codes in order to know whether the upload was successful or not.
Exit code 0 should only be used if everything was completed successfully.

**Comment by mbruel** [comment]
I've introduced some error codes when there is a error parsing the arguments:
```
    enum class ERROR_CODE : ushort {NONE=0, ERR_CONF_FILE, ERR_WRONG_ARG, ERR_NO_INPUT,
                                    ERR_DEL_AUTO, ERR_AUTO_NO_COMPRESS, ERR_AUTO_INPUT,
                                    ERR_MONITOR_NO_COMPRESS, ERR_MONITOR_INPUT,
                                    ERR_NB_THREAD, ERR_ARTICLE_SIZE, ERR_NB_RETRY, ERR_PAR2_ARGS,
                                    ERR_SERVER_REGEX, ERR_SERVER_PORT, ERR_SERVER_CONS,
                                    ERR_INPUT_READ
                                   };
```

It's going to be more difficult to get an error code if there is an error during the post as there could be several uploads scheduled if in auto or monitor mode. 
I'm not sure what I could do.... just keep the last error whether it's during the compression, the par2 generation or the upload...
@Tensai75 what do you think?

**Comment by Tensai75** [comment]
Hi Matthieu

thanks for picking this up.

> It's going to be more difficult to get an error code if there is an error during the post as there could be several uploads scheduled if in auto or monitor mode.
> I'm not sure what I could do.... just keep the last error whether it's during the compression, the par2 generation or the upload...
> @Tensai75 what do you think?

Well, if there are errors during the processing of the queue I would suggest to simply have an exit code which just states that ngPost completed its jobs but with some errors (e.g. COMPLETED_WITH_ERRORS). As far as I saw, this seems to be a common approach for similar programs with queue processing. Because the error messages during the processing are sent to stdout and the log, it is then the duty of the script or the user to check for the errors.

Regards, Tensai

**Comment by mbruel** [comment]
alright, that's sound an acceptable option, I'm going to put COMPLETED_WITH_ERRORS with value 1.
as you said, you can then check the log to have more details.

**Comment by mbruel** [comment]
ok that's done
