### ISSUE TITLE
Feature request: Configurable separator for history csv

### ISSUE THREAD

**Issue by peskdale** [mbruel/ngPost#65]
sHistoryLogFieldSeparator is currently [hardcoded](https://github.com/mbruel/ngPost/blob/master/src/NgPost.h#L256) as a semi-colon.

It would be great if this could be made to be a user configurable option in the config file, as some softwares expect a different character.

For example, the default setting for Excel in Windows is a comma, and there isn't an easy way to change this.

**Comment by peskdale** [comment]
Excel can save a file with any of those seperators, and it will ask you what you want to use  for regular text files. But for some weird reason it can only open CSV with a comma.

You can change a regional setting on Windows to fix it, but that the breaks formulas in normal spreadsheets... which is equally stupid.

Running a search and replace everytime I need to open it is rather tedious. But I think I’ve found a new workaround... will report back.

**Comment by AssRap3r** [comment]
just use data > from text and set delimiter as ;

**Comment by peskdale** [comment]
Unfortunately, there isn't a workaround that 'just works' for my use case - i.e. opening the CSV file directly, rather than importing it as suggested above.

Fortunately, this is github... so enjoy this PR.
