### ISSUE TITLE
Feature request: Immediate/short-term upload speed indication

### ISSUE THREAD

**Issue by peskdale** [mbruel/ngPost#67]
Splitting from #64...
It would be great for the GUI to have a more immediate or short-term speed indication to go alongside the total average. e.g. _Average speed over last 10 seconds_.

This is helpful when trying to manage network load, or diagnose possible upload speed issues.

**Comment by mbruel** [comment]
well, I've just tried to do something but in fact I'm not sure it is relevant...
I can't know the "exact speed" cause I'm just notified when the articles are posted, the whole article.
I've no way to know if it started before the timer or not...
so it might just indicate wrong speed. 
do you want to try what I've done and tell me? I'm in county side, I don't have a good connection, just 60kB/s :'(

**Comment by mbruel** [comment]
it's pushed, you can try.
with my shitty bandwidth I see the issue. With 2 connections, I'm getting 0 B/s most of the time and sometimes I get a pick to 120 kB/s then back to 0.

Maybe with decent bandwidth the problem is smoother... don't know, tell me what you think plz

**Comment by peskdale** [comment]
I'm on a 2MB/s connection, so I have a bit more bandwidth to play around with.

This seems to be working as expected. I'm getting a new reading every 5 seconds, which looks correct. Drops to zero shortly after I pause upload, which is also good.

The number did not appear until I actually started uploading data, which was a little odd. But I don;t think this is a huge problem.

Only suggestion for improvement is the placement in the GUI. This layout seemed to look okay:
`
    _ui->uploadLbl->setAlignment(Qt::AlignVCenter | Qt::AlignRight);
#ifdef __COMPUTE_IMMEDIATE_SPEED__
    _ui->uploadLbl->setText(QString("(%1 / %2) %3: %4\n%5: %6").arg(
                                nbArticlesUploaded).arg(
                                nbArticlesTotal).arg(
                                tr("avg speed")).arg(
                                avgSpeed).arg(
                                tr("avg speed (5s)")).arg(
                                immediateSpeed));
#else
`

**Comment by mbruel** [comment]
I'd rather let it first. I'll do some tests when I'm back home with a proper connection. see if I let 5 sec or less.

**Comment by mbruel** [comment]
I've added a tooltip and done the alignment directly in the ui file.
