### ISSUE TITLE
AutoPost - not using RAR_EXTRA

### ISSUE THREAD

**Issue by AssRap3r** [mbruel/ngPost#69]
maybe i'm having a brainlet moment but I can't get ngPost to use the RAR_EXTRA flags when using autopost

RAR_EXTRA = -ep1 -m0 -xRARBG.txt -xRARBG_DO_NOT_MIRROR.exe

ngPost --auto /downloads/TEST --compress --gen_par2 --gen_name -x

Compressing files: /usr/bin/rar a -ep1 -m0 -idp -v50m /tmp/b4XKTMnnGtRlrcco5DL8Q7/b4XKTMnnGtRlrcco5DL8Q7.rar /downloads/TEST/I.Am.Vengeance.Retaliation.2020.1080p.BluRay.H264.AAC-RARBG/ -r

wat do? :'(

**Comment by mbruel** [comment]
Indeed, it was forgotten when I changed the architecture to properly support multi-threading.
I've added it back.
Do you compile from source or you need me to provide a version? (if so what OS)

**Comment by AssRap3r** [comment]
I use the AppImg but can wait until the next version, was only testing the auto posting when i found the bug. not something i plan on using frequently.
