### ISSUE TITLE
Option -o: double extension .nzb.nzb

### ISSUE THREAD

**Issue by sanderjo** [mbruel/ngPost#7]
When I specify `-o /tmp/thisismyNZB.nzb` as the intended NZB file, it results in a nzb file `/tmp/thisismyNZB.nzb.nzb`, so double extension.

Is that how it was intended?

```
$ ./ngPost_v1.6-x86_64.AppImage  -h upload.super.nl -P 443 -s -u babla -p mypassword -n 5  -g "alt.binaries.test,alt.binaries.test2" -i /tmp/folderToP
ost -o /tmp/thisismyNZB.nzb
The default config file doesn't exist:  "/home/sander/.ngPost"

Upload size: 10 MB in 00:00:02.134 (2 sec) => average speed:   4.69 MB/s (5 connections on 4 threads)
nzb file: /tmp/thisismyNZB.nzb.nzb
```

**Comment by mbruel** [comment]
yep that's the desired behaviour, no need to put the extension when you use the -o option.
The reason of that is that when you don't specify the -o option, we will deduce the name of the nzb file using the basename of the first (or last, I'll have to check) file you wish to post (using -i option).
Thus, the .nzb is added in that case and even if you provided it with -o
I guess I could correct that, will do for the next release ;)

**Comment by sanderjo** [comment]
> The reason of that is that when you don't specify the -o option, we will deduce the name of the nzb file using the basename of the first (or last, I'll have to check) file you wish to post (using -i option).
> Thus, the .nzb is added in that case 

Yes, I understand that behavior.

> even if you provided it with -o

That I find strange.

> I guess I could correct that, will do for the next release ;)

Ah, nice!

**Comment by mbruel** [comment]
I've corrected it. Not tested but I'm quite confident.
It has been pushed but this doesn't worth making a new release, so you can build it yourself or wait 2020 for the v1.7 ;)

**Comment by sanderjo** [comment]
Yep, works!
```
sander@brixit:~/git/ngPost/src$ ./ngPost -h upload.super.nl -P 443 -s -u bla -p bla -n 5  -g "alt.binaries.test,alt.binaries.test2" -i /tmp/folderToPost -o /tmp/thisismyNZB---1734.nzb
The default config file doesn't exist:  "/home/sander/.ngPost"
Type conversion already registered from type QSharedPointer<QNetworkSession> to type QObject*

Upload size: 10 MB in 00:00:02.210 (2 sec) => average speed:   4.52 MB/s (5 connections on 4 threads)
nzb file: /tmp/thisismyNZB---1734.nzb

sander@brixit:~/git/ngPost/src$ ll /tmp/thisismyNZB---1734.nzb
-rw-rw-r-- 1 sander sander 1922 dec 31 17:34 /tmp/thisismyNZB---1734.nzb
sander@brixit:~/git/ngPost/src$ 
```
Nice!


FWIW: I believe the `Type conversion already registered from type QSharedPointer<QNetworkSession> to type QObject*` is new
