### ISSUE TITLE
Code copied from newsup - Please give proper attribution

### ISSUE THREAD

**Issue by demanuel** [mbruel/ngPost#71]
Hi!

I just noticed that you copied (even the variable names are the same!) and adapted the yenc encoding code from my project to c++

my code:
https://github.com/demanuel/NewsUP/blob/master/lib/NewsUP/yEnc.pm#L12

your code:
https://github.com/mbruel/ngPost/blob/master/src/utils/Yenc.cpp#L24

As required from GPLv3 **don't change the attribution!**

This link in stackexchange contains a good explanation of the license.
https://opensource.stackexchange.com/questions/4577/does-gplv3-require-attribution

How to give proper attribution:
https://softwareengineering.stackexchange.com/questions/167935/proper-attribution-of-derived-work-in-a-gpl-project

Thanks!

Regards,
David Santiago

**Comment by mbruel** [comment]
Hi David,
yep, I took your yEnc and made it pure C++.
I thought it was public domain as you don't have any header on your module
and if I remember I found several other implementations that were similar.
I thought I told you about it.
Indeed I kept the variable names, cause the goal was not to appropriate the
code to myself ;)

Are you happy with this header:
//========================================================================
//
// Copyright (C) 2019 Matthieu Bruel <Matthieu.Bruel@gmail.com>
// Copyright (C) 2018 David Emanuel Santiago
// Code derived from NewsUP project
// Thank you Tomas Novysedlak for yenc encoding piece :-)
// https://github.com/demanuel/NewsUP/commits/master/lib/NewsUP/yEnc.pm
//
//
// This file is a part of ngPost : https://github.com/mbruel/ngPost
//
// ngPost is free software; you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as
// published by the Free Software Foundation; version 3.0 of the License.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// You should have received a copy of the GNU Lesser General Public
// License along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301,
// USA.
//
//========================================================================

I'd only add it in the cpp file.

**Comment by demanuel** [comment]
Just this two lines are enough:

```
// Copyright (C) 2015-2018 David Emanuel Santiago and NewsUP contributors
// Code derived from NewsUP project
```

:-)

Thank you!

Regards,
David Santiago

**Comment by mbruel** [comment]
cool it's done :
https://github.com/mbruel/ngPost/blob/master/src/utils/Yenc.cpp
sorry to forgot to do it in the first place...
have you tried ngPost?

**Comment by demanuel** [comment]
> cool it's done 
Thank you :-)

> have you tried ngPost?
Yes i did. Once and it was fast :-)

Need to try it again :-)

Closing it.
