### ISSUE TITLE
Files are not saved

### ISSUE THREAD

**Issue by QualityMatters** [mbruel/ngPost#75]
Hi there, goodmorning. At the moment i'm testing ngpost. Very nice postprogram. Now i can create par2 files from very large files in 1 time 10%. Really happy with that, Quickpar cant do that. But here is the problem. When i post a file and shut down the program everything is gone and not saved. Is there a solution?

Greetings

**Comment by mbruel** [comment]
Hi,
don't shutdown the computer until the post(s) is(/are) finished...
There is the checkbox "shutdown computer" on the left of the choice of the language. Just enable it and ngPost will shutdown the computer when all the prepared posts are finished.
