### ISSUE TITLE
Feature Request: MONITOR_NZB_FOLDERS = true - also for --auto flag

### ISSUE THREAD

**Issue by noobcoder1983** [mbruel/ngPost#77]
Hi,

is it possible in command line use --auto /folder1 and nzb folder to /desired/nzb/folder1 --auto /folder2 and nzb to /desired/nzb/folder2?

Please implement that option which is used by --monitor also for --auto.

Thanks!

**Comment by noobcoder1983** [comment]
Hi,

is it possible in command line use --auto /folder1 and nzb folder to /desired/nzb/folder1 --auto /folder2 and nzb to /desired/nzb/folder2?

Please implement that option which is used by --monitor also for --auto.

Thanks!

**Comment by mbruel** [comment]
I'll try to add that in the next release ;)

**Comment by noobcoder1983** [comment]
Great thanks!

**Comment by mbruel** [comment]
done only for command line.
It uses the same configuration keyword MONITOR_FOLDERS
