### ISSUE TITLE
[Feature Request] post under different groups

### ISSUE THREAD

**Issue by terterterterter** [mbruel/ngPost#78]
would be nice to see ngpost be able to post each file to a different group

**Comment by mbruel** [comment]
@terterterterter it has been asked already.
I don't really see the interest... cf my [last comment here](https://github.com/mbruel/ngPost/issues/74#issuecomment-694925113).
Why would you like that?

**Comment by terterterterter** [comment]
it should increase obfuscation in case a search engine or an indexer is able to find the files in the future.

**Comment by mbruel** [comment]
have you read my comment?

> I don't see any benefit to change the poster for each file. It's better to use the same all the time so you can find your post in public indexer using the random name and password that are saved in the history file.
If you don't want to be indexed in public indexers, then you go use Article obfuscation but I don't encourage to use it.

What's the problem to find your post on public indexers? it's a good thing. Don't you use file name obfuscation? and a password?

**Comment by terterterterter** [comment]
have you read what I am asking?
your commend is about changing the poster for each file, I'm asking for something different.

Don't want to add a feature? Deny it and close the request.

**Comment by mbruel** [comment]
yep but it's the same thing.
I'd like to understand the benefit of things I do... having feature just to have feature what's the point? 
I may work on this but more to post each different posts (on the queue) on a different group, maybe not each file.

**Comment by mbruel** [comment]
Alright, I've implemented it.
If you want to beta test, here is an [AppImage for Linux](https://files.fm/u/sret3txy)

Basically in the Config File, you've to add the GROUP_POLICY. [cf here in the new conf](https://github.com/mbruel/ngPost/blob/8ec8a3c7b4e46357a96ad0c8bb87359690196fcd/ngPost.conf#L66)

By default it's ALL like before.
I would advise to use EACH_POST. But if you fancy, I've also added what you asked for (EACH_FILE)

**Comment by AssRap3r** [comment]
**YEEEEEEEEAH BOIIIIIIIII!**

testing and seems to work (y)

**Comment by mbruel** [comment]
@AssRap3r @terterterterter 
apparently some providers like newsxs consider that as spam and can ban you...

**Comment by terterterterter** [comment]
Seems to work good in my side.
Thank you for implementing it!

**Comment by dimqua** [comment]
Could someone explain what are the benefits of using this option?

**Comment by mbruel** [comment]
it is simple. It allows you to choose a number of groups and each post will be randomly posted on one of them.
it's for those who don't want to put all your post at the same place.... 
I don't really see the benefit either, except maybe if you post using all the time the same email....

**Comment by dimqua** [comment]
@mbruel but are there any benefits of using `ALL` or `EACH_FILE` instead? In your opinion.

**Comment by mbruel** [comment]
`EACH_FILE` shouldn't be used. it breaks indexers and I could be considering as spamming from providers.
`ALL` is nice for people who wants to post all the time on the same groups (can be single or several)
before it was only `ALL`. For me it's fine.
as it was requested I've added `EACH_POST` and because it was the same price, I've added `EACH_FILE`...

**Comment by Tensai75** [comment]
> `EACH_FILE` shouldn't be used. it breaks indexers and I could be considering as spamming from providers.

I strongly assist this statement. It is very bad behaviour to split up a post into different news groups and it doesn't make any sense unless you use obfuscation.

@mbruel : I would therefore suggest to allow the `EACH_FILE` option only together with obfuscation. Because otherwise it might lead to inexperienced people doing stupid things (I have seen enough of such posts already!).

**Comment by mbruel** [comment]
@Tensai75 yep good idea.
I'll probably also remove the Article obfuscation from the GUI, just let it cmd for experienced users.
Let's avoid spamming Usenet and keep indexers working as expected ;)
