### ISSUE TITLE
add possibility to switch in différent TMP_DIR

### ISSUE THREAD

**Issue by Diabolino** [mbruel/ngPost#79]
Added the possibility to change the temporary directory according to the size of the file

example using a tmpfs mount point

**Comment by mbruel** [comment]
It's implemented \o/
in the conf, you need to add [this](https://github.com/mbruel/ngPost/blob/62f949de8fb10399564d3ff2252113c148b702ba/ngPost.conf#L147)
```
## temporary folder with size constraint, typically a tmpfs partition
## the size of a post multiply by TMP_RAM_RATIO must available on the disk
## otherwise ngPost will use TMP_DIR (with no check)
## (uncomment the following line to activate the feature, make sure the path is writable)
TMP_RAM = /mnt/ngPost_tmpfs

## Ratio used on the source files size to compensate the par2 generation
## min is 10% to be sure (so 1.1), max 2.0
TMP_RAM_RATIO = 1.1
```

Maybe adjust the ratio depending on your PAR2_ARGS or your --par2_pct and it should work as expected :)
