### ISSUE TITLE
Cant use TMP_RAM on Windows

### ISSUE THREAD

**Issue by BiGfReAk1337** [mbruel/ngPost#80]
Hi
I set up a drive R: on windows with ImDisk Ramdisk:
https://sourceforge.net/projects/imdisk-toolkit/
I created a tmp folder and put that into the config file:
TMP_RAM = R:/tmp
But i always get the following error, when i start a post in ngPost:
"Couldn't use TMP_RAM as there is not enough space: -1.00 B available for a Post with ratio of 356.03 MB"

I tried both, a static and dynamic ramdisk, but both wont work

**Comment by mbruel** [comment]
Well I did the feature mainly for Linux users but it could work for Windows...
I don't have windows, just a VM. I can't really test.
What version do you use 32bit or 64bit?
I'm going to build you an exe with some extra logs around the result of QStorageInfo (Qt framework).
Please forward it to me. 
Depending on it, I'll raise an issue on Qt forum. (I won't fix it myself or use Windows API to get the disk space available)
Something you can do is try the behaviour with [another Ram disk application like this one](https://www.freewarefiles.com/SoftPerfect-RAM-Disk_program_94028.html).

**Comment by AssRap3r** [comment]
you can force it to use the ramdisk if you point TMP_DIR to the ramdisk but it's probably not advisable unless all your posts are small-ish

**Comment by mbruel** [comment]
it's working well with SoftPerfect RAM Disk 3.4.8.
you need to create a partition on the ram disk.

![](https://fv6.failiem.lv/thumb_show.php?i=3b43fbsz&view)

@AssRap3r if you've like 64GB of mem or more, you can easily use 16 GB for temporary files and thus be able to use it for ngPost for release <= 16 / 1.1 so 14.5GB. This is not small-ish is it?

**Comment by AssRap3r** [comment]
@mbruel i was thinking more of home-users that don't have server amounts of ram. then again my pc is quite old, maybe 32GB+ ram is normal these days :smile:  if you're using server hardware you're probably running linux anyway

**Comment by mbruel** [comment]
> @mbruel i was thinking more of home-users that don't have server amounts of ram. then again my pc is quite old, maybe 32GB+ ram is normal these days smile if you're using server hardware you're probably running linux anyway

yep that's true. I doubt Windows' users are really concerned with that feature.... (I was quite surprised with to see that Issue raised). If they have 16GB it should already be more than enough.

Anyway even with 16GB (what I have on my professional laptop running on Debian), you could dedicate 4GB to 8GB in RAM for temp files. This could be enough for certain type of posting (Music, SD releases...)

The "cool point" of TMP_RAM is that the size of the post is checked and it will automatically use the default TMP_DIR if the post wouldn't fit in RAM ;)

**Comment by BiGfReAk1337** [comment]
Thank you for your quick support.
Its working now with SoftPerfect RAM Disk.
That small feature is so important and nice and underrated i think. It will preserve my ssd alot.

**Comment by mbruel** [comment]
@BiGfReAk1337 just out of curiosity, how much RAM do you have on your Windows environment? (32 GB?)
How big do you make the Ram Disk? (16 GB?)

about the feature, I wouldn't have thought about it for ngPost, it was a request from my community from someone having lost several SSD after 3 to 6 months...
For me it's not an app with massive I/Os but yeah if it is running 24/7 maybe could be...
I use it in general professionally for simulation apps having hundreds of I/Os per sec.
