### ISSUE TITLE
ngPost uses TMP_RAM even when folder is too big

### ISSUE THREAD

**Issue by BiGfReAk1337** [mbruel/ngPost#81]
Hi
as i mentioned in my last issue thread, the TMP_RAM feature is working now on windows (64bit) with softperfect ram disk.
But i have another issue now.
ngPost is trying to use the TMP_RAM path, even when the folder is way too big. 
i.e. it tries to zip a folder which is 31gb on a ram disk which is only 14gb. When the ram disk is full, ngPost says that this drive is full and whether i want to try again or abort. 
But the config file says, that the TMP_RAM path will only be used, when ramdisk_freespace > file_to_post*tmp_ratio
Otherwise it will use the TMP_DIR path. This somehow doesnt work.

The strange thing is, that in die logging window it says:
Start Post #1: folder.nzb
Using TMP_RAM path as temporary folder. Post size: -934485754.00 B
I dont know why the size is negative nor why it is ~900MB. In fakt it is like i mentioned around 31GB

**Comment by mbruel** [comment]
My bad... I used an int to store the size of your folders. It has a[ "small" min and max values](https://www.geeksforgeeks.org/int_max-int_min-cc-applications/) which is below  2.2 billions. When you go over the max, you're going in the negatives... That is why....

[Here is a compiled version for win64](https://files.fm/u/djxmkhkr).
Please confirm it is working as expected now :)

with a qint64 you can go up to 9,223,372,036,854,775,807 which is like more than 9223 Petabytes. You should be safe ;)

**Comment by mbruel** [comment]
@BiGfReAk1337 an update on this? I'm waiting for you feedback to release the v4.14

**Comment by BiGfReAk1337** [comment]
Hi @mbruel 
sry, i wasnt at home over the weekend.
I just tested the new version without issues (logging below). 
Thanks for your quick support! 


> Using RAM Storage R:/tmp, root: R:/, type: NTFS, size: 13.67 GB, available: 13.60 GB
> Start Post #1: The Quest.nzb
> Couldn't use TMP_RAM as there is not enough space: 13.60 GB available for a Post with ratio of 40.47 GB
> 
> Compressing files...
> **********

**Comment by BiGfReAk1337** [comment]
Hi @mbruel
sry, i wasnt at home over the weekend.
I just tested the new version without issues (logging below).
Thanks for your quick support!

> 
> Using RAM Storage R:/tmp, root: R:/, type: NTFS, size: 13.67 GB, available: 13.60 GB
> Start Post #1: folder.nzb
> Couldn't use TMP_RAM as there is not enough space: 13.60 GB available for a Post with ratio of 40.47 GB
> 
> Compressing files...

**Comment by mbruel** [comment]
Cool ;)
