### ISSUE TITLE
The queue stops if a file is deleted and PREPARE_PACKING is set to true

### ISSUE THREAD

**Issue by Uukrull** [mbruel/ngPost#82]
This is a queue with five files on a monitored folder:

![image](https://user-images.githubusercontent.com/5891591/96365277-bd365b00-113f-11eb-861a-222ee0469470.png)

If I delete de 2.zip file, the queue stops with the error "next active job different to the packing one..." but it's still active active because if I close ngPost, it throws a warning about ngpost is currently posting.

With PREPARE_PACKING set to false, if I delete the 2.zip, the queue continues with 5.zip and 4.zip
Ideally, it would be better to be able to delete the 2.zip job from the list but that's not possible with a monitored folder (you can delete it from the list, but ngPost will still try to post it)

![image](https://user-images.githubusercontent.com/5891591/96365494-397d6e00-1141-11eb-90a1-43c47d259c53.png)

**Comment by mbruel** [comment]
@Uukrull 
give it a try, normally the bug with PREPARE_PACKING should be fixed. Please confirm ;)

**Comment by Uukrull** [comment]
Yes. Confirmed working.

Many thanks!

**Comment by mbruel** [comment]
@Uukrull I don't have much time to allow the removal of queued jobs.
so instead I've removed its possibility ;)
you can't select anymore, press DEL or do right click when you're in Monitoring mode.
At least it won't be confusing.
