### ISSUE TITLE
Monitor - process individual files in subfolders

### ISSUE THREAD

**Issue by AssRap3r** [mbruel/ngPost#83]
Is it possible for ngPost to sequentially post individual files in subfolders when using monitor mode? 

setup:
ruTorrent autodl -> download directory -> Autotools move into monitored directory

cmd:
ngPost --monitor /downloads/torrents/complete --rm_posted --compress --gen_par2 --gen_name -x

if for example there's a folder with 13 episodes ngPost will rar the entire folder instead of each file

**Comment by mbruel** [comment]
why don't you make your auto-tool to move the content of the folders instead of the folders?
problem solved no...

PS: no need to have --gen_name if you use -x ;)

**Comment by AssRap3r** [comment]
Autotools is a plugin for rutorrent and doesn't seem to support removing the folder and placing files into a root directory, it will always be move.directory/torrent.name

**Comment by mbruel** [comment]
hum...
could do then but I don't have time nowadays.
remind me in few months ;)

**Comment by mbruel** [comment]
but it's a bit tricky.... how do you now if the folder contains several episode or if it's a single movie with a Subs folder?

**Comment by AssRap3r** [comment]
i agree...it will be complicated because of the different file/folder structures. it'll be the responsibility of the user to properly configure their monitoring, auto-move and rss/irssi setings because it's an advanced feature and there isn't going to be one-size-fits-all setting. 

some idea of what i'm thinking:

TV Season Pack:
```
show.s01-grp/s01e01.mkv
show.s01-grp/s01e02.mkv
show.s01-grp/s01e03.mkv
```
ngPost --monitor-files /downloads/trackers/complete/TV-HD
rar matching filetypes in the directory "TV-HD" and subdirectories "TV-HD/show.s01-grp" (config or flag option to traverse subdirectories?)

Movie BD:
```
Movie.2020/BDMV
Movie.2020/CERTIFICATE
```
ngPost --monitor-folders /downloads/trackers/complete/Movie-BD
would pack new top-level folders in directory "Movie-BD" (existing --monitor behavior)

TV BD:
```
Show.S01-grp\DISC1
Show.S01-grp\DISC1\BDMV
Show.S01-grp\DISC1\CERTIFICATE
Show.S01-grp\DISC2\BDMV
Show.S01-grp\DISC2\CERTIFICATE
```
ngPost --monitor-subfolders /downloads/trackers/complete/TV-BD
would enter each directory in "TV-BD" and rar each folder top-level subfolder separately (ie: DISC1\*.* then DISC2\*.* etc..)
