### ISSUE TITLE
 Filename upload problem with ngPost

### ISSUE THREAD

**Issue by noobcoder1983** [mbruel/ngPost#86]
I have a problem with uploading specific filename with ngPost. NgPost ignores them if there are not in the folder:

Example:

'filename'$'\343\203\251\343\203\273\343\203\240\343\203\251\343\203\274\343\203\212'' 2 [55000F0003004][v0].txt'

How I can solve that, that ngPost upload that filename too?

**Comment by mbruel** [comment]
I'm not sure what you mean...
I've no issue posting such file. 
[Here is an nzb file](https://files.fm/u/hxs3cghk) of what I could post. (single file no compression.)
Is it only the name of the nzb that is different that what you'd expect?

**Comment by noobcoder1983** [comment]
Thanks, hmm really strange the issue was caused by this in` /etc/ssh/ssh_config`

`SendEnv LANG LC_*`

When deactivating it, ngPost works fine now.

Hmm maybe you could mention it in the Readme to prevent this?

**Comment by noobcoder1983** [comment]
Supplement:

Posting now works but japanese and korean chars will be cutted and are lost in the finished .nzb file.

Like: ジョン [00004FF003030][v1234].txt will transform to [00004FF003030][v1234].nzb

**Comment by mbruel** [comment]
yep easy fix for that: just disable  or comment this in the conf:
```
## remove accents and special characters from the nzb file names
NZB_RM_ACCENTS = true
```

**Comment by noobcoder1983** [comment]
Ok thanks I forgot about that feature. :-)

**Comment by mbruel** [comment]
so I guess I can close this issue right?

**Comment by noobcoder1983** [comment]
Yeah thank you I think so.
