### ISSUE TITLE
[Bug] NZB_POST_CMD breaks with cURL "=" character

### ISSUE THREAD

**Issue by AssRap3r** [mbruel/ngPost#87]
nzb_post_cmd breaks when = is present in a cURL command. some indexers require form data to be specified when posting to their API

example:
```
NZB_POST_CMD = curl -X POST -F 'file=@__nzbPath__' -F 'api=12345' -F 'cat=45" -F "private=no" https://usenet.com/post-api
```

output from ngPost:
```
NZB Post cmd: "curl -X POST -F 'nzb exitcode: -2
Warning: Illegally formatted input field!
curl: option -F: is badly used here
```

**Comment by mbruel** [comment]
There is a previously Qt function that is used to parse the line and split the command and each arguments in order to then launch the process. It has been removed from Qt cause it has certain issues...
I've chosen to use it as for what I've seen it's working good if the input is good.
Your line has issues, especially you're opening a single quote around `cat=45` and closing it with a double quote.

Anyway, try to only use single quotes, it should work. Otherwise only double quotes but you might need to escape them with a `\\` not sure... Try first single quotes, it's the safest ;)

```
    QString fullCmd = "curl -X POST -F 'file=@__nzbPath__' -F 'api=12345' -F 'cat=45' -F 'private=no' https://usenet.com/post-api";
    fullCmd.replace("__nzbPath__", "/tmp/nzb/test.nzb");

    QStringList args = NgPost::parseCombinedArgString(fullCmd);
    QString     cmd  = args.takeFirst();
    qDebug() << "cmd: " << cmd << ", args: " << args;
    return 0;
```
donne en sortie:
`cmd:  "curl" , args:  ("-X", "POST", "-F", "'file=@/tmp/nzb/test.nzb'", "-F", "'api=12345'", "-F", "'cat=45'", "-F", "'private=no'", "https://usenet.com/post-api")`
Ce qui me semblerai bon....

**Comment by AssRap3r** [comment]
Ignore the quote errors - i edited the command before posting it.

have you tried putting your command in .ngPost and trying an upload? it doesn't work. even when copying your QString fullCmd it fails. it's the = which is causing the problem and is repeatable

ngPost config + error codes
Normal command, nothing edited. Errors out at file=@
```
NZB_POST_CMD = curl -X POST -F 'file=@__nzbPath__' -F 'api=12345' -F 'cat=45' -F 'private=no' https://usenet.com/post-api
NZB Post cmd: curl -X POST -F 'file exitcode: 2
```

Edited command, removed first =. nzb path is correctly echoed, fails at api= 
```
NZB_POST_CMD = curl -X POST -F 'file@__nzbPath__' -F 'api=12345' -F 'cat=45' -F 'private=no' https://usenet.com/post-api 
NZB Post cmd: curl -X POST -F 'file@/var/tmp/norar_56.nzb' -F 'api exitcode: 2
```

Edited command, removed first and second = for file & api. errors on cat=
```
NZB_POST_CMD = curl -X POST -F 'file@__nzbPath__' -F 'api 12345' -F 'cat=45' -F 'private=no' https://usenet.com/post-api 
NZB Post cmd: curl -X POST -F 'file@/var/tmp/norar_56.nzb' -F 'api 12345' -F 'cat exitcode: 2
```

now just messing around:

```
NZB_POST_CMD = echo "The number of articles = __nbArticles__ "
echo The number of articles
NZB Post cmd: echo "The number of articles exitcode: 0
```

```
NZB_POST_CMD = echo "__nbArticles__ = number of articles"
echo 1
NZB Post cmd: echo "1 exitcode: 0
```

**Comment by mbruel** [comment]
I'm going to check. I've tested quickly without reading from the conf and there is no pb.
```
    QString fullCmd = "echo  \"echo1 'release=__nzbPath__' end\"";
    fullCmd.replace("__nzbPath__", "/tmp/nzb/test.nzb");

    QStringList args = parseCombinedArgString(fullCmd); //QProcess::splitCommand(fullCmd);
    QString     cmd  = args.takeFirst();

    int res = QProcess::execute(cmd, args);
    qDebug() << "cmd: " << cmd << ", args: " << args << " => exitCode: " << res;
    return 0;
```
give this output: 
```
echo1 'release=/tmp/nzb/test.nzb' end
cmd:  "echo" , args:  ("echo1 'release=/tmp/nzb/test.nzb' end")  => exitCode:  0
```

But indeed there is a problem with `NZB_POST_CMD = echo "echo1 'release=__nzbName__' end"`
weird...

**Comment by mbruel** [comment]
@AssRap3r ok my bad, you were right, there is an issue with the `=`.
That's because I'm reading in the conf with `Config_Keyword = Value` so I'm cutting on the `=`
I've made a fix for the NZB_POST_CMD. I suppose it is the only one were there could be some `=`.
Can you build from source and try or do you need me to build?
I've tried an I got this issue:
```
fullCmd:  "curl -X POST -F 'file=@/tmp/fontawesome-free-5.0.13_1.nzb' -F 'api=12345' -F 'cat=45' -F 'private=no' https://usenet.com/post-api"
Warning: setting file /tmp/fontawesome-free-5.0.13_1.nzb'  failed!
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   175    0     0    0   175      0    383 --:--:-- --:--:-- --:--:--   383
curl: (26) read function returned funny value
cmd:  "curl" , args:  ("-X", "POST", "-F", "'file=@/tmp/fontawesome-free-5.0.13_1.nzb'", "-F", "'api=12345'", "-F", "'cat=45'", "-F", "'private=no'", "https://usenet.com/post-api")  => exitCode:  26
```

**Comment by AssRap3r** [comment]
@mbruel it works but you need to either enclose parts in " or not at all. ' causes error

```
curl -X POST -F 'file=@__nzbPath__' -F 'api=12345' -F 'cat=45' -F 'private=no' https://usenet.com/post-api
```
will give you setting file failed & exitCode:  26

curl -X POST -F "file=@__nzbPath__" -F "api=12345" -F "cat=45" -F "private=no" https://usenet.com/post-api
{"status":200,"status_message":"NZB added","data":{"title":"test's_1","guid":"12345"}}NZB Post cmd: curl -X POST -F "nzb=@/tmp/test's_1.nzb" -F "apikey=1234567" https://usenet.com/api exitcode: 0

**Comment by mbruel** [comment]
cool!
I recommand you to enclose in double quotes rather than nothing in case there are spaces in the path ;)

**Comment by AssRap3r** [comment]
@mbruel still appears to be some errors with special characters
```
[06:31:58.153] nzb file: /tmp/nzbs/Warrior (2019) S02E06 To a Man with a Hammer, Everything Looks Like a Nail (1080p AMZN Webrip x265 10bit EAC3 5.1 - Goki)[TAoE].nzb
Warning: setting file /tmp/nzbs/Warrior (2019) S02E06 To a Man with a Hammer
Warning: failed!
Warning: setting file Everything Looks Like a Nail (1080p AMZN Webrip x265
Warning: 10bit EAC3 5.1 - Goki)[TAoE].nzb  failed!
curl: (26) read function returned funny value
```
I'm using the double quotes like in the example. the nzb is output fine, the curl command shows the proper filename but the command isn't executed.

**Comment by mbruel** [comment]
I don't know man, try using a script that does the curl, maybe it would help...
ngPost is supposed to print out the command it is executing just after it is done.... what is it?
