### ISSUE TITLE
"file name obfuscation" checkbox doesn't stay checked

### ISSUE THREAD

**Issue by swinokur** [mbruel/ngPost#93]
Hi,
I'm trying to use the "file name obfuscation" feature, but that checkbox seems to keep resetting itself to unchecked. 

(This is on ngpost 4.14)

I looked in the .conf file to see if there was a way to manually set that, but didn't see anything obvious.

thanks!

**Comment by mbruel** [comment]
yeah it's not saved.
the feature has been added on request but is not promoted...

**Comment by swinokur** [comment]
ah, thanks for the update!

**Comment by dimqua** [comment]
Is there a reason why the filename obfuscation is not promoted, as you said?

**Comment by mbruel** [comment]
@dimqua cause it is boring for the end user and that nowadays the norm is to use a random name and password for the archive no?
