### ISSUE TITLE
[Enhancement] Binary for Linux/Ubuntu

### ISSUE THREAD

**Issue by kaputeko** [mbruel/ngPost#95]
I use a seedbox where **I can't install anything.**

Would it be possible to release an already compiled release that works on debian base systems with a **parpar binary** also compatible with debian?

The current version compiled for debian does not work on command line.

In seedbox I don't have a graphical interface just the terminal.

Thanks in advance.

**Comment by mbruel** [comment]
What error do you have when you try to launch it?
Use at least one argument (like --help) otherwise it will try to launch the GUi.
Have you tried both appimage? Check the _debian8 one if you're Debian is old

**Comment by mbruel** [comment]
Hum do you've an issue with parpar only or ngPost?

**Comment by kaputeko** [comment]
I did it.
I extracted the ngPost_v4.14-x86_64_debian8.AppImage file and managed to use it as command line in my seedbox.

**Comment by mbruel** [comment]
@kaputeko what do you mean extract? you can just make it executable (`chmod 755 ngPost_v4.14-x86_64_debian8.AppImage` ) and then run it, no need to extract ;)

**Comment by kaputeko** [comment]
Not really @mbruel 

As I said at the beginning, I use ngPost in a seedbox only per terminal. I have no graphical interface and can't install anything.
When I try to run the program it does: 

> QXcbConnection: Could not connect to display
> Aborted

Then I extracted the *.AppImage file and got access to the ngPost binary and parpar.

**Comment by mbruel** [comment]
@kaputeko when you get this `QXcbConnection: Could not connect to display` are you adding argument to the command line? like --help?

when you extract the AppImage and access parpar and ngPost binary, are you able to use ngPost then? Or do you get the same error?

**Comment by kaputeko** [comment]
How stupid I was
You're right
I can use the  ./ngPost_v4.14-x86_64_debian8.AppImage by command line.

> when you extract the AppImage and access parpar and ngPost binary, are you able to use ngPost then? Or do you get the same error?

Yes, after unpacking I can use it normally.
Actually I am now in doubt about how to configure the conf file using the *.AppImage command line. I guess I would have to base it on the github conf file, right?

**Comment by mbruel** [comment]
Yep, download the conf from github and store it as `~/.ngPost`
You can then edit it to add your server details and whatever option you wish to use.
(To download you can do: `wget https://raw.githubusercontent.com/mbruel/ngPost/master/ngPost.conf -O ~/.ngPost`

Happy you like ngPost :)

**Comment by kaputeko** [comment]
Is there a possibility to put the usenet provider's encrypted user and password in the configuration file?

**Comment by mbruel** [comment]
no it's not possible. 
if you really want you could either encrypt the whole config file using openssl and decrypt it when launching ngPost using `-c` or another option would be to not save your server settings in the config file and use `-h news.xxx.com -P 443 -s -u $USER -p $PASS -n 30`

**Comment by kaputeko** [comment]
Thank you for your answer. 

I have another question:

I know it is possible to set a password for the RAR but is there any way that this password will not be discovered by the NZB download client?

I noticed that even without me entering the password, when loading NZB the program that is downloading already finds the RAR password automatically.

Thank you very much for clearing up my doubts.

**Comment by mbruel** [comment]
that's on purpose, the nzb file contains the password in its header.
there is no benefit to have the nzb and password separate...

**Comment by kaputeko** [comment]
So what is the benefit of the csv file that stores the file passwords?

**Comment by mbruel** [comment]
The CSV allows you to create another nzb file from public indexers. That one will not contain the password so you need it aside.
But from the one generated by ngPost no need ;)

**Comment by kaputeko** [comment]
So if I want nobody to ever find nzb I have to activate the obfurcation right? activating it is impossible for someone to find my nzb? In my head I thought ... if someone finds my nzb, he would have to know the rar password.

**Comment by mbruel** [comment]
don't use article obfuscation, it would make the CSV file useless.
as you said, if you've a password, nobody will be able to extract your archive except if you give them the password OR the nzb file generated by ngPost.

**Comment by kaputeko** [comment]
I don't think I'm being clear. How do I generate the nzb file without the password in it? I want to use ngPost to create nzb etc. Is there a way?

**Comment by mbruel** [comment]
no there is no way that ngPost doesn't add the password in the nzb cause as I said most people prefer to have it inside.
you can remove it manually.... (just edit the nzb with a text editor and remove the header.)
but why would you want to remove it?

**Comment by mbruel** [comment]
in fact you can use a post command in ngPost to do it for you using `grep -v '<meta type="password">'` for example

**Comment by kaputeko** [comment]
I am afraid that someone outside my circle will catch the nzbs. I don't want it to be public at all. Then I thought ... If someone gets the nzb, they won't know the password to unzip it.

**Comment by mbruel** [comment]
people have other things to do then brute forcing usenet stuff without knowing what's inside...
use random name and password and nobody without the password will access your files.

**Comment by kaputeko** [comment]
I am very dumb.
Thank you for your patience.
Now I finally understand.
Even if the public indexers can find my nzb articles and publish them, they won't have my RAR password, right?

**Comment by mbruel** [comment]
yes that's right ;)
so better not use article obfuscation so you can use the history csv file as a backup. you'll be the only one having the couple (name of the post, password)

**Comment by kaputeko** [comment]
If I don't use obfuscation it's easier for providers to index my upload, right?
It will be harder to corrupt because it will be in more places.
Or it has nothing to do with it?
