### ISSUE TITLE
[Feature Request] Folder monitoring in config

### ISSUE THREAD

**Issue by AssRap3r** [mbruel/ngPost#96]
Feature: 
Allow specifying folders to monitor in .ngPost config file. Instead of throwing a syntax error when --monitor is used without a folder it should instead look in the config file for the relevant folders to monitor. 

Reason: 
(Mentioned briefly in #90 ) - If monitoring multiple folders you need to run a separate ngPost instance for each one. since PREPARE_PACKING isn't respected between instances you can end up sharing ram, cpu, hdd and posting connections which can significantly slow down each post. It should also decrease overall ram usage - for example, my 2 currently monitoring instances are using 63MB and 119MB ram each, both with 1760+MB Virtual memory. for the times when I need to monitor even more, the ram usage is up to 700MB total + 1.7GB of virtual for each additional instance. bigly sad.

**Comment by mbruel** [comment]
do you know that you can monitor several folders in one instance of ngPost?
you can do: `ngPost --monitor downloads/TrackerA --monitor downloads/TrackerB --monitor downloads/TrackerC  --compress --gen_par2 --gen_name --disp_progress files`
and `ngPost -c //.ngPost2 --monitor downloads/TrackerA2 --monitor downloads/TrackerB2 --monitor downloads/TrackerC2 --compress --gen_par2 --gen_name --disp_progress files`
you'll divide per 3 your memory usage ;)

I don't really see the benefit of having the monitors in config. it's extra work for me and I suppose people using the GUI would not like it so I'd have to keep both at the same time...
I'll think about it when I do the work for #90 

PS: you can just use an alias with the whole command if you always monitor the same folders.

**Comment by AssRap3r** [comment]
@mbruel i wasn't aware you could specify multiple folders in the CLI, in that case there's no need for config monitoring since it can be achieved with 2 instances, then once #90 is implemented will be down to 1. now have 7 monitors with only 2 processes which is much better :+1: 

not sure how many other people were aware of this, would be good to include an example with multiple folders in the output Examples

**Comment by mbruel** [comment]
I've updated the examples:
```
Examples:
  - with monitoring: ngPost --monitor /data/folder1 --monitor /data/folder2 --auto_compress --rm_posted --disp_progress files
  - with auto post: ngPost --auto /data/folder1 --auto /data/folder2 --compress --gen_par2 --gen_name --gen_pass --rar_size 42 --disp_progress files
  - with compression, filename obfuscation, random password and par2: ngPost -i /tmp/file1 -i /tmp/folder1 -o /nzb/myPost.nzb --compress --gen_name --gen_pass --gen_par2
  - with config file: ngPost -c ~/.ngPost -m "password=qwerty42" -f ngPost@nowhere.com -i /tmp/file1 -i /tmp/file2 -i /tmp/folderToPost1 -i /tmp/folderToPost2
  - with all params:  ngPost -t 1 -m "password=qwerty42" -m "metaKey=someValue" -h news.newshosting.com -P 443 -s -u user -p pass -n 30 -f ngPost@nowhere.com  -g "alt.binaries.test,alt.binaries.test2" -a 64000 -i /tmp/folderToPost -o /tmp/folderToPost.nzb
```

Basically the main syntax is telling it: `Syntax: ngPost (options)* (-i <file or folder> | --auto <folder> | --monitor <folder>)+`
in formal language theory the `*` means: 0 to several and the `+` means: at least 1. But I guess not so many people are aware of that even in IT....
